// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: approvalqueue.proto

package protosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protos "sonic-trivia/backend/protos"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApprovalQueueServiceName is the fully-qualified name of the ApprovalQueueService service.
	ApprovalQueueServiceName = "protos.ApprovalQueueService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApprovalQueueServiceAddToQueueProcedure is the fully-qualified name of the ApprovalQueueService's
	// AddToQueue RPC.
	ApprovalQueueServiceAddToQueueProcedure = "/protos.ApprovalQueueService/AddToQueue"
	// ApprovalQueueServiceRemoveFromQueueProcedure is the fully-qualified name of the
	// ApprovalQueueService's RemoveFromQueue RPC.
	ApprovalQueueServiceRemoveFromQueueProcedure = "/protos.ApprovalQueueService/RemoveFromQueue"
	// ApprovalQueueServiceGetAllApprovalRequestsProcedure is the fully-qualified name of the
	// ApprovalQueueService's GetAllApprovalRequests RPC.
	ApprovalQueueServiceGetAllApprovalRequestsProcedure = "/protos.ApprovalQueueService/GetAllApprovalRequests"
	// ApprovalQueueServiceApproveRequestProcedure is the fully-qualified name of the
	// ApprovalQueueService's ApproveRequest RPC.
	ApprovalQueueServiceApproveRequestProcedure = "/protos.ApprovalQueueService/ApproveRequest"
	// ApprovalQueueServiceStreamApprovalQueueProcedure is the fully-qualified name of the
	// ApprovalQueueService's StreamApprovalQueue RPC.
	ApprovalQueueServiceStreamApprovalQueueProcedure = "/protos.ApprovalQueueService/StreamApprovalQueue"
)

// ApprovalQueueServiceClient is a client for the protos.ApprovalQueueService service.
type ApprovalQueueServiceClient interface {
	AddToQueue(context.Context, *connect.Request[protos.AddToQueueRequest]) (*connect.Response[protos.AddToQueueResponse], error)
	RemoveFromQueue(context.Context, *connect.Request[protos.RemoveFromQueueRequest]) (*connect.Response[protos.RemoveFromQueueResponse], error)
	GetAllApprovalRequests(context.Context, *connect.Request[protos.GetAllApprovalRequestsRequest]) (*connect.Response[protos.GetAllApprovalRequestsResponse], error)
	ApproveRequest(context.Context, *connect.Request[protos.ApproveRequestRequest]) (*connect.Response[protos.ApproveRequestResponse], error)
	StreamApprovalQueue(context.Context, *connect.Request[protos.StreamApprovalQueueRequest]) (*connect.ServerStreamForClient[protos.ApprovalQueueUpdate], error)
}

// NewApprovalQueueServiceClient constructs a client for the protos.ApprovalQueueService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApprovalQueueServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApprovalQueueServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	approvalQueueServiceMethods := protos.File_approvalqueue_proto.Services().ByName("ApprovalQueueService").Methods()
	return &approvalQueueServiceClient{
		addToQueue: connect.NewClient[protos.AddToQueueRequest, protos.AddToQueueResponse](
			httpClient,
			baseURL+ApprovalQueueServiceAddToQueueProcedure,
			connect.WithSchema(approvalQueueServiceMethods.ByName("AddToQueue")),
			connect.WithClientOptions(opts...),
		),
		removeFromQueue: connect.NewClient[protos.RemoveFromQueueRequest, protos.RemoveFromQueueResponse](
			httpClient,
			baseURL+ApprovalQueueServiceRemoveFromQueueProcedure,
			connect.WithSchema(approvalQueueServiceMethods.ByName("RemoveFromQueue")),
			connect.WithClientOptions(opts...),
		),
		getAllApprovalRequests: connect.NewClient[protos.GetAllApprovalRequestsRequest, protos.GetAllApprovalRequestsResponse](
			httpClient,
			baseURL+ApprovalQueueServiceGetAllApprovalRequestsProcedure,
			connect.WithSchema(approvalQueueServiceMethods.ByName("GetAllApprovalRequests")),
			connect.WithClientOptions(opts...),
		),
		approveRequest: connect.NewClient[protos.ApproveRequestRequest, protos.ApproveRequestResponse](
			httpClient,
			baseURL+ApprovalQueueServiceApproveRequestProcedure,
			connect.WithSchema(approvalQueueServiceMethods.ByName("ApproveRequest")),
			connect.WithClientOptions(opts...),
		),
		streamApprovalQueue: connect.NewClient[protos.StreamApprovalQueueRequest, protos.ApprovalQueueUpdate](
			httpClient,
			baseURL+ApprovalQueueServiceStreamApprovalQueueProcedure,
			connect.WithSchema(approvalQueueServiceMethods.ByName("StreamApprovalQueue")),
			connect.WithClientOptions(opts...),
		),
	}
}

// approvalQueueServiceClient implements ApprovalQueueServiceClient.
type approvalQueueServiceClient struct {
	addToQueue             *connect.Client[protos.AddToQueueRequest, protos.AddToQueueResponse]
	removeFromQueue        *connect.Client[protos.RemoveFromQueueRequest, protos.RemoveFromQueueResponse]
	getAllApprovalRequests *connect.Client[protos.GetAllApprovalRequestsRequest, protos.GetAllApprovalRequestsResponse]
	approveRequest         *connect.Client[protos.ApproveRequestRequest, protos.ApproveRequestResponse]
	streamApprovalQueue    *connect.Client[protos.StreamApprovalQueueRequest, protos.ApprovalQueueUpdate]
}

// AddToQueue calls protos.ApprovalQueueService.AddToQueue.
func (c *approvalQueueServiceClient) AddToQueue(ctx context.Context, req *connect.Request[protos.AddToQueueRequest]) (*connect.Response[protos.AddToQueueResponse], error) {
	return c.addToQueue.CallUnary(ctx, req)
}

// RemoveFromQueue calls protos.ApprovalQueueService.RemoveFromQueue.
func (c *approvalQueueServiceClient) RemoveFromQueue(ctx context.Context, req *connect.Request[protos.RemoveFromQueueRequest]) (*connect.Response[protos.RemoveFromQueueResponse], error) {
	return c.removeFromQueue.CallUnary(ctx, req)
}

// GetAllApprovalRequests calls protos.ApprovalQueueService.GetAllApprovalRequests.
func (c *approvalQueueServiceClient) GetAllApprovalRequests(ctx context.Context, req *connect.Request[protos.GetAllApprovalRequestsRequest]) (*connect.Response[protos.GetAllApprovalRequestsResponse], error) {
	return c.getAllApprovalRequests.CallUnary(ctx, req)
}

// ApproveRequest calls protos.ApprovalQueueService.ApproveRequest.
func (c *approvalQueueServiceClient) ApproveRequest(ctx context.Context, req *connect.Request[protos.ApproveRequestRequest]) (*connect.Response[protos.ApproveRequestResponse], error) {
	return c.approveRequest.CallUnary(ctx, req)
}

// StreamApprovalQueue calls protos.ApprovalQueueService.StreamApprovalQueue.
func (c *approvalQueueServiceClient) StreamApprovalQueue(ctx context.Context, req *connect.Request[protos.StreamApprovalQueueRequest]) (*connect.ServerStreamForClient[protos.ApprovalQueueUpdate], error) {
	return c.streamApprovalQueue.CallServerStream(ctx, req)
}

// ApprovalQueueServiceHandler is an implementation of the protos.ApprovalQueueService service.
type ApprovalQueueServiceHandler interface {
	AddToQueue(context.Context, *connect.Request[protos.AddToQueueRequest]) (*connect.Response[protos.AddToQueueResponse], error)
	RemoveFromQueue(context.Context, *connect.Request[protos.RemoveFromQueueRequest]) (*connect.Response[protos.RemoveFromQueueResponse], error)
	GetAllApprovalRequests(context.Context, *connect.Request[protos.GetAllApprovalRequestsRequest]) (*connect.Response[protos.GetAllApprovalRequestsResponse], error)
	ApproveRequest(context.Context, *connect.Request[protos.ApproveRequestRequest]) (*connect.Response[protos.ApproveRequestResponse], error)
	StreamApprovalQueue(context.Context, *connect.Request[protos.StreamApprovalQueueRequest], *connect.ServerStream[protos.ApprovalQueueUpdate]) error
}

// NewApprovalQueueServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApprovalQueueServiceHandler(svc ApprovalQueueServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	approvalQueueServiceMethods := protos.File_approvalqueue_proto.Services().ByName("ApprovalQueueService").Methods()
	approvalQueueServiceAddToQueueHandler := connect.NewUnaryHandler(
		ApprovalQueueServiceAddToQueueProcedure,
		svc.AddToQueue,
		connect.WithSchema(approvalQueueServiceMethods.ByName("AddToQueue")),
		connect.WithHandlerOptions(opts...),
	)
	approvalQueueServiceRemoveFromQueueHandler := connect.NewUnaryHandler(
		ApprovalQueueServiceRemoveFromQueueProcedure,
		svc.RemoveFromQueue,
		connect.WithSchema(approvalQueueServiceMethods.ByName("RemoveFromQueue")),
		connect.WithHandlerOptions(opts...),
	)
	approvalQueueServiceGetAllApprovalRequestsHandler := connect.NewUnaryHandler(
		ApprovalQueueServiceGetAllApprovalRequestsProcedure,
		svc.GetAllApprovalRequests,
		connect.WithSchema(approvalQueueServiceMethods.ByName("GetAllApprovalRequests")),
		connect.WithHandlerOptions(opts...),
	)
	approvalQueueServiceApproveRequestHandler := connect.NewUnaryHandler(
		ApprovalQueueServiceApproveRequestProcedure,
		svc.ApproveRequest,
		connect.WithSchema(approvalQueueServiceMethods.ByName("ApproveRequest")),
		connect.WithHandlerOptions(opts...),
	)
	approvalQueueServiceStreamApprovalQueueHandler := connect.NewServerStreamHandler(
		ApprovalQueueServiceStreamApprovalQueueProcedure,
		svc.StreamApprovalQueue,
		connect.WithSchema(approvalQueueServiceMethods.ByName("StreamApprovalQueue")),
		connect.WithHandlerOptions(opts...),
	)
	return "/protos.ApprovalQueueService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApprovalQueueServiceAddToQueueProcedure:
			approvalQueueServiceAddToQueueHandler.ServeHTTP(w, r)
		case ApprovalQueueServiceRemoveFromQueueProcedure:
			approvalQueueServiceRemoveFromQueueHandler.ServeHTTP(w, r)
		case ApprovalQueueServiceGetAllApprovalRequestsProcedure:
			approvalQueueServiceGetAllApprovalRequestsHandler.ServeHTTP(w, r)
		case ApprovalQueueServiceApproveRequestProcedure:
			approvalQueueServiceApproveRequestHandler.ServeHTTP(w, r)
		case ApprovalQueueServiceStreamApprovalQueueProcedure:
			approvalQueueServiceStreamApprovalQueueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApprovalQueueServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApprovalQueueServiceHandler struct{}

func (UnimplementedApprovalQueueServiceHandler) AddToQueue(context.Context, *connect.Request[protos.AddToQueueRequest]) (*connect.Response[protos.AddToQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.ApprovalQueueService.AddToQueue is not implemented"))
}

func (UnimplementedApprovalQueueServiceHandler) RemoveFromQueue(context.Context, *connect.Request[protos.RemoveFromQueueRequest]) (*connect.Response[protos.RemoveFromQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.ApprovalQueueService.RemoveFromQueue is not implemented"))
}

func (UnimplementedApprovalQueueServiceHandler) GetAllApprovalRequests(context.Context, *connect.Request[protos.GetAllApprovalRequestsRequest]) (*connect.Response[protos.GetAllApprovalRequestsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.ApprovalQueueService.GetAllApprovalRequests is not implemented"))
}

func (UnimplementedApprovalQueueServiceHandler) ApproveRequest(context.Context, *connect.Request[protos.ApproveRequestRequest]) (*connect.Response[protos.ApproveRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.ApprovalQueueService.ApproveRequest is not implemented"))
}

func (UnimplementedApprovalQueueServiceHandler) StreamApprovalQueue(context.Context, *connect.Request[protos.StreamApprovalQueueRequest], *connect.ServerStream[protos.ApprovalQueueUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("protos.ApprovalQueueService.StreamApprovalQueue is not implemented"))
}
