// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: guessthatsong.proto

package protosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protos "sonic-trivia/backend/protos"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GuessThatSongServiceName is the fully-qualified name of the GuessThatSongService service.
	GuessThatSongServiceName = "protos.GuessThatSongService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GuessThatSongServiceCreateSongProcedure is the fully-qualified name of the GuessThatSongService's
	// CreateSong RPC.
	GuessThatSongServiceCreateSongProcedure = "/protos.GuessThatSongService/CreateSong"
	// GuessThatSongServiceGetSongProcedure is the fully-qualified name of the GuessThatSongService's
	// GetSong RPC.
	GuessThatSongServiceGetSongProcedure = "/protos.GuessThatSongService/GetSong"
	// GuessThatSongServiceGetRandomSongProcedure is the fully-qualified name of the
	// GuessThatSongService's GetRandomSong RPC.
	GuessThatSongServiceGetRandomSongProcedure = "/protos.GuessThatSongService/GetRandomSong"
	// GuessThatSongServiceGetRandomSongsProcedure is the fully-qualified name of the
	// GuessThatSongService's GetRandomSongs RPC.
	GuessThatSongServiceGetRandomSongsProcedure = "/protos.GuessThatSongService/GetRandomSongs"
	// GuessThatSongServiceUpdateSongProcedure is the fully-qualified name of the GuessThatSongService's
	// UpdateSong RPC.
	GuessThatSongServiceUpdateSongProcedure = "/protos.GuessThatSongService/UpdateSong"
	// GuessThatSongServiceDeleteSongProcedure is the fully-qualified name of the GuessThatSongService's
	// DeleteSong RPC.
	GuessThatSongServiceDeleteSongProcedure = "/protos.GuessThatSongService/DeleteSong"
	// GuessThatSongServiceSearchSongProcedure is the fully-qualified name of the GuessThatSongService's
	// SearchSong RPC.
	GuessThatSongServiceSearchSongProcedure = "/protos.GuessThatSongService/SearchSong"
)

// GuessThatSongServiceClient is a client for the protos.GuessThatSongService service.
type GuessThatSongServiceClient interface {
	CreateSong(context.Context, *connect.Request[protos.CreateSongRequest]) (*connect.Response[protos.CreateSongResponse], error)
	GetSong(context.Context, *connect.Request[protos.GetSongRequest]) (*connect.Response[protos.GetSongResponse], error)
	GetRandomSong(context.Context, *connect.Request[protos.GetRandomSongRequest]) (*connect.Response[protos.GetRandomSongResponse], error)
	GetRandomSongs(context.Context, *connect.Request[protos.GetRandomSongsRequest]) (*connect.Response[protos.GetRandomSongsResponse], error)
	UpdateSong(context.Context, *connect.Request[protos.UpdateSongRequest]) (*connect.Response[protos.UpdateSongResponse], error)
	DeleteSong(context.Context, *connect.Request[protos.DeleteSongRequest]) (*connect.Response[protos.DeleteSongResponse], error)
	SearchSong(context.Context, *connect.Request[protos.SearchSongRequest]) (*connect.Response[protos.SearchSongResponse], error)
}

// NewGuessThatSongServiceClient constructs a client for the protos.GuessThatSongService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGuessThatSongServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GuessThatSongServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	guessThatSongServiceMethods := protos.File_guessthatsong_proto.Services().ByName("GuessThatSongService").Methods()
	return &guessThatSongServiceClient{
		createSong: connect.NewClient[protos.CreateSongRequest, protos.CreateSongResponse](
			httpClient,
			baseURL+GuessThatSongServiceCreateSongProcedure,
			connect.WithSchema(guessThatSongServiceMethods.ByName("CreateSong")),
			connect.WithClientOptions(opts...),
		),
		getSong: connect.NewClient[protos.GetSongRequest, protos.GetSongResponse](
			httpClient,
			baseURL+GuessThatSongServiceGetSongProcedure,
			connect.WithSchema(guessThatSongServiceMethods.ByName("GetSong")),
			connect.WithClientOptions(opts...),
		),
		getRandomSong: connect.NewClient[protos.GetRandomSongRequest, protos.GetRandomSongResponse](
			httpClient,
			baseURL+GuessThatSongServiceGetRandomSongProcedure,
			connect.WithSchema(guessThatSongServiceMethods.ByName("GetRandomSong")),
			connect.WithClientOptions(opts...),
		),
		getRandomSongs: connect.NewClient[protos.GetRandomSongsRequest, protos.GetRandomSongsResponse](
			httpClient,
			baseURL+GuessThatSongServiceGetRandomSongsProcedure,
			connect.WithSchema(guessThatSongServiceMethods.ByName("GetRandomSongs")),
			connect.WithClientOptions(opts...),
		),
		updateSong: connect.NewClient[protos.UpdateSongRequest, protos.UpdateSongResponse](
			httpClient,
			baseURL+GuessThatSongServiceUpdateSongProcedure,
			connect.WithSchema(guessThatSongServiceMethods.ByName("UpdateSong")),
			connect.WithClientOptions(opts...),
		),
		deleteSong: connect.NewClient[protos.DeleteSongRequest, protos.DeleteSongResponse](
			httpClient,
			baseURL+GuessThatSongServiceDeleteSongProcedure,
			connect.WithSchema(guessThatSongServiceMethods.ByName("DeleteSong")),
			connect.WithClientOptions(opts...),
		),
		searchSong: connect.NewClient[protos.SearchSongRequest, protos.SearchSongResponse](
			httpClient,
			baseURL+GuessThatSongServiceSearchSongProcedure,
			connect.WithSchema(guessThatSongServiceMethods.ByName("SearchSong")),
			connect.WithClientOptions(opts...),
		),
	}
}

// guessThatSongServiceClient implements GuessThatSongServiceClient.
type guessThatSongServiceClient struct {
	createSong     *connect.Client[protos.CreateSongRequest, protos.CreateSongResponse]
	getSong        *connect.Client[protos.GetSongRequest, protos.GetSongResponse]
	getRandomSong  *connect.Client[protos.GetRandomSongRequest, protos.GetRandomSongResponse]
	getRandomSongs *connect.Client[protos.GetRandomSongsRequest, protos.GetRandomSongsResponse]
	updateSong     *connect.Client[protos.UpdateSongRequest, protos.UpdateSongResponse]
	deleteSong     *connect.Client[protos.DeleteSongRequest, protos.DeleteSongResponse]
	searchSong     *connect.Client[protos.SearchSongRequest, protos.SearchSongResponse]
}

// CreateSong calls protos.GuessThatSongService.CreateSong.
func (c *guessThatSongServiceClient) CreateSong(ctx context.Context, req *connect.Request[protos.CreateSongRequest]) (*connect.Response[protos.CreateSongResponse], error) {
	return c.createSong.CallUnary(ctx, req)
}

// GetSong calls protos.GuessThatSongService.GetSong.
func (c *guessThatSongServiceClient) GetSong(ctx context.Context, req *connect.Request[protos.GetSongRequest]) (*connect.Response[protos.GetSongResponse], error) {
	return c.getSong.CallUnary(ctx, req)
}

// GetRandomSong calls protos.GuessThatSongService.GetRandomSong.
func (c *guessThatSongServiceClient) GetRandomSong(ctx context.Context, req *connect.Request[protos.GetRandomSongRequest]) (*connect.Response[protos.GetRandomSongResponse], error) {
	return c.getRandomSong.CallUnary(ctx, req)
}

// GetRandomSongs calls protos.GuessThatSongService.GetRandomSongs.
func (c *guessThatSongServiceClient) GetRandomSongs(ctx context.Context, req *connect.Request[protos.GetRandomSongsRequest]) (*connect.Response[protos.GetRandomSongsResponse], error) {
	return c.getRandomSongs.CallUnary(ctx, req)
}

// UpdateSong calls protos.GuessThatSongService.UpdateSong.
func (c *guessThatSongServiceClient) UpdateSong(ctx context.Context, req *connect.Request[protos.UpdateSongRequest]) (*connect.Response[protos.UpdateSongResponse], error) {
	return c.updateSong.CallUnary(ctx, req)
}

// DeleteSong calls protos.GuessThatSongService.DeleteSong.
func (c *guessThatSongServiceClient) DeleteSong(ctx context.Context, req *connect.Request[protos.DeleteSongRequest]) (*connect.Response[protos.DeleteSongResponse], error) {
	return c.deleteSong.CallUnary(ctx, req)
}

// SearchSong calls protos.GuessThatSongService.SearchSong.
func (c *guessThatSongServiceClient) SearchSong(ctx context.Context, req *connect.Request[protos.SearchSongRequest]) (*connect.Response[protos.SearchSongResponse], error) {
	return c.searchSong.CallUnary(ctx, req)
}

// GuessThatSongServiceHandler is an implementation of the protos.GuessThatSongService service.
type GuessThatSongServiceHandler interface {
	CreateSong(context.Context, *connect.Request[protos.CreateSongRequest]) (*connect.Response[protos.CreateSongResponse], error)
	GetSong(context.Context, *connect.Request[protos.GetSongRequest]) (*connect.Response[protos.GetSongResponse], error)
	GetRandomSong(context.Context, *connect.Request[protos.GetRandomSongRequest]) (*connect.Response[protos.GetRandomSongResponse], error)
	GetRandomSongs(context.Context, *connect.Request[protos.GetRandomSongsRequest]) (*connect.Response[protos.GetRandomSongsResponse], error)
	UpdateSong(context.Context, *connect.Request[protos.UpdateSongRequest]) (*connect.Response[protos.UpdateSongResponse], error)
	DeleteSong(context.Context, *connect.Request[protos.DeleteSongRequest]) (*connect.Response[protos.DeleteSongResponse], error)
	SearchSong(context.Context, *connect.Request[protos.SearchSongRequest]) (*connect.Response[protos.SearchSongResponse], error)
}

// NewGuessThatSongServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGuessThatSongServiceHandler(svc GuessThatSongServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	guessThatSongServiceMethods := protos.File_guessthatsong_proto.Services().ByName("GuessThatSongService").Methods()
	guessThatSongServiceCreateSongHandler := connect.NewUnaryHandler(
		GuessThatSongServiceCreateSongProcedure,
		svc.CreateSong,
		connect.WithSchema(guessThatSongServiceMethods.ByName("CreateSong")),
		connect.WithHandlerOptions(opts...),
	)
	guessThatSongServiceGetSongHandler := connect.NewUnaryHandler(
		GuessThatSongServiceGetSongProcedure,
		svc.GetSong,
		connect.WithSchema(guessThatSongServiceMethods.ByName("GetSong")),
		connect.WithHandlerOptions(opts...),
	)
	guessThatSongServiceGetRandomSongHandler := connect.NewUnaryHandler(
		GuessThatSongServiceGetRandomSongProcedure,
		svc.GetRandomSong,
		connect.WithSchema(guessThatSongServiceMethods.ByName("GetRandomSong")),
		connect.WithHandlerOptions(opts...),
	)
	guessThatSongServiceGetRandomSongsHandler := connect.NewUnaryHandler(
		GuessThatSongServiceGetRandomSongsProcedure,
		svc.GetRandomSongs,
		connect.WithSchema(guessThatSongServiceMethods.ByName("GetRandomSongs")),
		connect.WithHandlerOptions(opts...),
	)
	guessThatSongServiceUpdateSongHandler := connect.NewUnaryHandler(
		GuessThatSongServiceUpdateSongProcedure,
		svc.UpdateSong,
		connect.WithSchema(guessThatSongServiceMethods.ByName("UpdateSong")),
		connect.WithHandlerOptions(opts...),
	)
	guessThatSongServiceDeleteSongHandler := connect.NewUnaryHandler(
		GuessThatSongServiceDeleteSongProcedure,
		svc.DeleteSong,
		connect.WithSchema(guessThatSongServiceMethods.ByName("DeleteSong")),
		connect.WithHandlerOptions(opts...),
	)
	guessThatSongServiceSearchSongHandler := connect.NewUnaryHandler(
		GuessThatSongServiceSearchSongProcedure,
		svc.SearchSong,
		connect.WithSchema(guessThatSongServiceMethods.ByName("SearchSong")),
		connect.WithHandlerOptions(opts...),
	)
	return "/protos.GuessThatSongService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GuessThatSongServiceCreateSongProcedure:
			guessThatSongServiceCreateSongHandler.ServeHTTP(w, r)
		case GuessThatSongServiceGetSongProcedure:
			guessThatSongServiceGetSongHandler.ServeHTTP(w, r)
		case GuessThatSongServiceGetRandomSongProcedure:
			guessThatSongServiceGetRandomSongHandler.ServeHTTP(w, r)
		case GuessThatSongServiceGetRandomSongsProcedure:
			guessThatSongServiceGetRandomSongsHandler.ServeHTTP(w, r)
		case GuessThatSongServiceUpdateSongProcedure:
			guessThatSongServiceUpdateSongHandler.ServeHTTP(w, r)
		case GuessThatSongServiceDeleteSongProcedure:
			guessThatSongServiceDeleteSongHandler.ServeHTTP(w, r)
		case GuessThatSongServiceSearchSongProcedure:
			guessThatSongServiceSearchSongHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGuessThatSongServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGuessThatSongServiceHandler struct{}

func (UnimplementedGuessThatSongServiceHandler) CreateSong(context.Context, *connect.Request[protos.CreateSongRequest]) (*connect.Response[protos.CreateSongResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.GuessThatSongService.CreateSong is not implemented"))
}

func (UnimplementedGuessThatSongServiceHandler) GetSong(context.Context, *connect.Request[protos.GetSongRequest]) (*connect.Response[protos.GetSongResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.GuessThatSongService.GetSong is not implemented"))
}

func (UnimplementedGuessThatSongServiceHandler) GetRandomSong(context.Context, *connect.Request[protos.GetRandomSongRequest]) (*connect.Response[protos.GetRandomSongResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.GuessThatSongService.GetRandomSong is not implemented"))
}

func (UnimplementedGuessThatSongServiceHandler) GetRandomSongs(context.Context, *connect.Request[protos.GetRandomSongsRequest]) (*connect.Response[protos.GetRandomSongsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.GuessThatSongService.GetRandomSongs is not implemented"))
}

func (UnimplementedGuessThatSongServiceHandler) UpdateSong(context.Context, *connect.Request[protos.UpdateSongRequest]) (*connect.Response[protos.UpdateSongResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.GuessThatSongService.UpdateSong is not implemented"))
}

func (UnimplementedGuessThatSongServiceHandler) DeleteSong(context.Context, *connect.Request[protos.DeleteSongRequest]) (*connect.Response[protos.DeleteSongResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.GuessThatSongService.DeleteSong is not implemented"))
}

func (UnimplementedGuessThatSongServiceHandler) SearchSong(context.Context, *connect.Request[protos.SearchSongRequest]) (*connect.Response[protos.SearchSongResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.GuessThatSongService.SearchSong is not implemented"))
}
