// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: leaderboard.proto

package protosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protos "sonic-trivia/backend/protos"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LeaderboardServiceName is the fully-qualified name of the LeaderboardService service.
	LeaderboardServiceName = "protos.LeaderboardService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LeaderboardServiceUpdateRoomLeaderboardProcedure is the fully-qualified name of the
	// LeaderboardService's UpdateRoomLeaderboard RPC.
	LeaderboardServiceUpdateRoomLeaderboardProcedure = "/protos.LeaderboardService/UpdateRoomLeaderboard"
	// LeaderboardServicePaginateRoomLeaderboardProcedure is the fully-qualified name of the
	// LeaderboardService's PaginateRoomLeaderboard RPC.
	LeaderboardServicePaginateRoomLeaderboardProcedure = "/protos.LeaderboardService/PaginateRoomLeaderboard"
	// LeaderboardServiceUpdateGlobalLeaderboardProcedure is the fully-qualified name of the
	// LeaderboardService's UpdateGlobalLeaderboard RPC.
	LeaderboardServiceUpdateGlobalLeaderboardProcedure = "/protos.LeaderboardService/UpdateGlobalLeaderboard"
	// LeaderboardServicePaginateGlobalLeaderboardProcedure is the fully-qualified name of the
	// LeaderboardService's PaginateGlobalLeaderboard RPC.
	LeaderboardServicePaginateGlobalLeaderboardProcedure = "/protos.LeaderboardService/PaginateGlobalLeaderboard"
)

// LeaderboardServiceClient is a client for the protos.LeaderboardService service.
type LeaderboardServiceClient interface {
	UpdateRoomLeaderboard(context.Context, *connect.Request[protos.UpdateRoomLeaderboardRequest]) (*connect.Response[protos.UpdateRoomLeaderboardResponse], error)
	PaginateRoomLeaderboard(context.Context, *connect.Request[protos.PaginateRoomLeaderboardRequest]) (*connect.Response[protos.PaginateRoomLeaderboardResponse], error)
	UpdateGlobalLeaderboard(context.Context, *connect.Request[protos.UpdateGlobalLeaderboardRequest]) (*connect.Response[protos.UpdateGlobalLeaderboardResponse], error)
	PaginateGlobalLeaderboard(context.Context, *connect.Request[protos.PaginateGlobalLeaderboardRequest]) (*connect.Response[protos.PaginateGlobalLeaderboardResponse], error)
}

// NewLeaderboardServiceClient constructs a client for the protos.LeaderboardService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLeaderboardServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LeaderboardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	leaderboardServiceMethods := protos.File_leaderboard_proto.Services().ByName("LeaderboardService").Methods()
	return &leaderboardServiceClient{
		updateRoomLeaderboard: connect.NewClient[protos.UpdateRoomLeaderboardRequest, protos.UpdateRoomLeaderboardResponse](
			httpClient,
			baseURL+LeaderboardServiceUpdateRoomLeaderboardProcedure,
			connect.WithSchema(leaderboardServiceMethods.ByName("UpdateRoomLeaderboard")),
			connect.WithClientOptions(opts...),
		),
		paginateRoomLeaderboard: connect.NewClient[protos.PaginateRoomLeaderboardRequest, protos.PaginateRoomLeaderboardResponse](
			httpClient,
			baseURL+LeaderboardServicePaginateRoomLeaderboardProcedure,
			connect.WithSchema(leaderboardServiceMethods.ByName("PaginateRoomLeaderboard")),
			connect.WithClientOptions(opts...),
		),
		updateGlobalLeaderboard: connect.NewClient[protos.UpdateGlobalLeaderboardRequest, protos.UpdateGlobalLeaderboardResponse](
			httpClient,
			baseURL+LeaderboardServiceUpdateGlobalLeaderboardProcedure,
			connect.WithSchema(leaderboardServiceMethods.ByName("UpdateGlobalLeaderboard")),
			connect.WithClientOptions(opts...),
		),
		paginateGlobalLeaderboard: connect.NewClient[protos.PaginateGlobalLeaderboardRequest, protos.PaginateGlobalLeaderboardResponse](
			httpClient,
			baseURL+LeaderboardServicePaginateGlobalLeaderboardProcedure,
			connect.WithSchema(leaderboardServiceMethods.ByName("PaginateGlobalLeaderboard")),
			connect.WithClientOptions(opts...),
		),
	}
}

// leaderboardServiceClient implements LeaderboardServiceClient.
type leaderboardServiceClient struct {
	updateRoomLeaderboard     *connect.Client[protos.UpdateRoomLeaderboardRequest, protos.UpdateRoomLeaderboardResponse]
	paginateRoomLeaderboard   *connect.Client[protos.PaginateRoomLeaderboardRequest, protos.PaginateRoomLeaderboardResponse]
	updateGlobalLeaderboard   *connect.Client[protos.UpdateGlobalLeaderboardRequest, protos.UpdateGlobalLeaderboardResponse]
	paginateGlobalLeaderboard *connect.Client[protos.PaginateGlobalLeaderboardRequest, protos.PaginateGlobalLeaderboardResponse]
}

// UpdateRoomLeaderboard calls protos.LeaderboardService.UpdateRoomLeaderboard.
func (c *leaderboardServiceClient) UpdateRoomLeaderboard(ctx context.Context, req *connect.Request[protos.UpdateRoomLeaderboardRequest]) (*connect.Response[protos.UpdateRoomLeaderboardResponse], error) {
	return c.updateRoomLeaderboard.CallUnary(ctx, req)
}

// PaginateRoomLeaderboard calls protos.LeaderboardService.PaginateRoomLeaderboard.
func (c *leaderboardServiceClient) PaginateRoomLeaderboard(ctx context.Context, req *connect.Request[protos.PaginateRoomLeaderboardRequest]) (*connect.Response[protos.PaginateRoomLeaderboardResponse], error) {
	return c.paginateRoomLeaderboard.CallUnary(ctx, req)
}

// UpdateGlobalLeaderboard calls protos.LeaderboardService.UpdateGlobalLeaderboard.
func (c *leaderboardServiceClient) UpdateGlobalLeaderboard(ctx context.Context, req *connect.Request[protos.UpdateGlobalLeaderboardRequest]) (*connect.Response[protos.UpdateGlobalLeaderboardResponse], error) {
	return c.updateGlobalLeaderboard.CallUnary(ctx, req)
}

// PaginateGlobalLeaderboard calls protos.LeaderboardService.PaginateGlobalLeaderboard.
func (c *leaderboardServiceClient) PaginateGlobalLeaderboard(ctx context.Context, req *connect.Request[protos.PaginateGlobalLeaderboardRequest]) (*connect.Response[protos.PaginateGlobalLeaderboardResponse], error) {
	return c.paginateGlobalLeaderboard.CallUnary(ctx, req)
}

// LeaderboardServiceHandler is an implementation of the protos.LeaderboardService service.
type LeaderboardServiceHandler interface {
	UpdateRoomLeaderboard(context.Context, *connect.Request[protos.UpdateRoomLeaderboardRequest]) (*connect.Response[protos.UpdateRoomLeaderboardResponse], error)
	PaginateRoomLeaderboard(context.Context, *connect.Request[protos.PaginateRoomLeaderboardRequest]) (*connect.Response[protos.PaginateRoomLeaderboardResponse], error)
	UpdateGlobalLeaderboard(context.Context, *connect.Request[protos.UpdateGlobalLeaderboardRequest]) (*connect.Response[protos.UpdateGlobalLeaderboardResponse], error)
	PaginateGlobalLeaderboard(context.Context, *connect.Request[protos.PaginateGlobalLeaderboardRequest]) (*connect.Response[protos.PaginateGlobalLeaderboardResponse], error)
}

// NewLeaderboardServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLeaderboardServiceHandler(svc LeaderboardServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	leaderboardServiceMethods := protos.File_leaderboard_proto.Services().ByName("LeaderboardService").Methods()
	leaderboardServiceUpdateRoomLeaderboardHandler := connect.NewUnaryHandler(
		LeaderboardServiceUpdateRoomLeaderboardProcedure,
		svc.UpdateRoomLeaderboard,
		connect.WithSchema(leaderboardServiceMethods.ByName("UpdateRoomLeaderboard")),
		connect.WithHandlerOptions(opts...),
	)
	leaderboardServicePaginateRoomLeaderboardHandler := connect.NewUnaryHandler(
		LeaderboardServicePaginateRoomLeaderboardProcedure,
		svc.PaginateRoomLeaderboard,
		connect.WithSchema(leaderboardServiceMethods.ByName("PaginateRoomLeaderboard")),
		connect.WithHandlerOptions(opts...),
	)
	leaderboardServiceUpdateGlobalLeaderboardHandler := connect.NewUnaryHandler(
		LeaderboardServiceUpdateGlobalLeaderboardProcedure,
		svc.UpdateGlobalLeaderboard,
		connect.WithSchema(leaderboardServiceMethods.ByName("UpdateGlobalLeaderboard")),
		connect.WithHandlerOptions(opts...),
	)
	leaderboardServicePaginateGlobalLeaderboardHandler := connect.NewUnaryHandler(
		LeaderboardServicePaginateGlobalLeaderboardProcedure,
		svc.PaginateGlobalLeaderboard,
		connect.WithSchema(leaderboardServiceMethods.ByName("PaginateGlobalLeaderboard")),
		connect.WithHandlerOptions(opts...),
	)
	return "/protos.LeaderboardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LeaderboardServiceUpdateRoomLeaderboardProcedure:
			leaderboardServiceUpdateRoomLeaderboardHandler.ServeHTTP(w, r)
		case LeaderboardServicePaginateRoomLeaderboardProcedure:
			leaderboardServicePaginateRoomLeaderboardHandler.ServeHTTP(w, r)
		case LeaderboardServiceUpdateGlobalLeaderboardProcedure:
			leaderboardServiceUpdateGlobalLeaderboardHandler.ServeHTTP(w, r)
		case LeaderboardServicePaginateGlobalLeaderboardProcedure:
			leaderboardServicePaginateGlobalLeaderboardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLeaderboardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLeaderboardServiceHandler struct{}

func (UnimplementedLeaderboardServiceHandler) UpdateRoomLeaderboard(context.Context, *connect.Request[protos.UpdateRoomLeaderboardRequest]) (*connect.Response[protos.UpdateRoomLeaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.LeaderboardService.UpdateRoomLeaderboard is not implemented"))
}

func (UnimplementedLeaderboardServiceHandler) PaginateRoomLeaderboard(context.Context, *connect.Request[protos.PaginateRoomLeaderboardRequest]) (*connect.Response[protos.PaginateRoomLeaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.LeaderboardService.PaginateRoomLeaderboard is not implemented"))
}

func (UnimplementedLeaderboardServiceHandler) UpdateGlobalLeaderboard(context.Context, *connect.Request[protos.UpdateGlobalLeaderboardRequest]) (*connect.Response[protos.UpdateGlobalLeaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.LeaderboardService.UpdateGlobalLeaderboard is not implemented"))
}

func (UnimplementedLeaderboardServiceHandler) PaginateGlobalLeaderboard(context.Context, *connect.Request[protos.PaginateGlobalLeaderboardRequest]) (*connect.Response[protos.PaginateGlobalLeaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.LeaderboardService.PaginateGlobalLeaderboard is not implemented"))
}
