// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: login.proto

package protosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protos "sonic-trivia/backend/protos"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LoginServiceName is the fully-qualified name of the LoginService service.
	LoginServiceName = "protos.LoginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LoginServiceLoginProcedure is the fully-qualified name of the LoginService's Login RPC.
	LoginServiceLoginProcedure = "/protos.LoginService/Login"
	// LoginServiceSocialMediaLoginProcedure is the fully-qualified name of the LoginService's
	// SocialMediaLogin RPC.
	LoginServiceSocialMediaLoginProcedure = "/protos.LoginService/SocialMediaLogin"
	// LoginServiceSignUpUsernameOrEmailProcedure is the fully-qualified name of the LoginService's
	// SignUpUsernameOrEmail RPC.
	LoginServiceSignUpUsernameOrEmailProcedure = "/protos.LoginService/SignUpUsernameOrEmail"
)

// LoginServiceClient is a client for the protos.LoginService service.
type LoginServiceClient interface {
	Login(context.Context, *connect.Request[protos.LoginRequest]) (*connect.Response[protos.LoginResponse], error)
	SocialMediaLogin(context.Context, *connect.Request[protos.SocialMediaLoginRequest]) (*connect.Response[protos.SocialMediaLoginResponse], error)
	SignUpUsernameOrEmail(context.Context, *connect.Request[protos.SignUpUsernameOrEmailRequest]) (*connect.Response[protos.SignUpUsernameOrEmailResponse], error)
}

// NewLoginServiceClient constructs a client for the protos.LoginService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLoginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LoginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	loginServiceMethods := protos.File_login_proto.Services().ByName("LoginService").Methods()
	return &loginServiceClient{
		login: connect.NewClient[protos.LoginRequest, protos.LoginResponse](
			httpClient,
			baseURL+LoginServiceLoginProcedure,
			connect.WithSchema(loginServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		socialMediaLogin: connect.NewClient[protos.SocialMediaLoginRequest, protos.SocialMediaLoginResponse](
			httpClient,
			baseURL+LoginServiceSocialMediaLoginProcedure,
			connect.WithSchema(loginServiceMethods.ByName("SocialMediaLogin")),
			connect.WithClientOptions(opts...),
		),
		signUpUsernameOrEmail: connect.NewClient[protos.SignUpUsernameOrEmailRequest, protos.SignUpUsernameOrEmailResponse](
			httpClient,
			baseURL+LoginServiceSignUpUsernameOrEmailProcedure,
			connect.WithSchema(loginServiceMethods.ByName("SignUpUsernameOrEmail")),
			connect.WithClientOptions(opts...),
		),
	}
}

// loginServiceClient implements LoginServiceClient.
type loginServiceClient struct {
	login                 *connect.Client[protos.LoginRequest, protos.LoginResponse]
	socialMediaLogin      *connect.Client[protos.SocialMediaLoginRequest, protos.SocialMediaLoginResponse]
	signUpUsernameOrEmail *connect.Client[protos.SignUpUsernameOrEmailRequest, protos.SignUpUsernameOrEmailResponse]
}

// Login calls protos.LoginService.Login.
func (c *loginServiceClient) Login(ctx context.Context, req *connect.Request[protos.LoginRequest]) (*connect.Response[protos.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// SocialMediaLogin calls protos.LoginService.SocialMediaLogin.
func (c *loginServiceClient) SocialMediaLogin(ctx context.Context, req *connect.Request[protos.SocialMediaLoginRequest]) (*connect.Response[protos.SocialMediaLoginResponse], error) {
	return c.socialMediaLogin.CallUnary(ctx, req)
}

// SignUpUsernameOrEmail calls protos.LoginService.SignUpUsernameOrEmail.
func (c *loginServiceClient) SignUpUsernameOrEmail(ctx context.Context, req *connect.Request[protos.SignUpUsernameOrEmailRequest]) (*connect.Response[protos.SignUpUsernameOrEmailResponse], error) {
	return c.signUpUsernameOrEmail.CallUnary(ctx, req)
}

// LoginServiceHandler is an implementation of the protos.LoginService service.
type LoginServiceHandler interface {
	Login(context.Context, *connect.Request[protos.LoginRequest]) (*connect.Response[protos.LoginResponse], error)
	SocialMediaLogin(context.Context, *connect.Request[protos.SocialMediaLoginRequest]) (*connect.Response[protos.SocialMediaLoginResponse], error)
	SignUpUsernameOrEmail(context.Context, *connect.Request[protos.SignUpUsernameOrEmailRequest]) (*connect.Response[protos.SignUpUsernameOrEmailResponse], error)
}

// NewLoginServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLoginServiceHandler(svc LoginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	loginServiceMethods := protos.File_login_proto.Services().ByName("LoginService").Methods()
	loginServiceLoginHandler := connect.NewUnaryHandler(
		LoginServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(loginServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	loginServiceSocialMediaLoginHandler := connect.NewUnaryHandler(
		LoginServiceSocialMediaLoginProcedure,
		svc.SocialMediaLogin,
		connect.WithSchema(loginServiceMethods.ByName("SocialMediaLogin")),
		connect.WithHandlerOptions(opts...),
	)
	loginServiceSignUpUsernameOrEmailHandler := connect.NewUnaryHandler(
		LoginServiceSignUpUsernameOrEmailProcedure,
		svc.SignUpUsernameOrEmail,
		connect.WithSchema(loginServiceMethods.ByName("SignUpUsernameOrEmail")),
		connect.WithHandlerOptions(opts...),
	)
	return "/protos.LoginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LoginServiceLoginProcedure:
			loginServiceLoginHandler.ServeHTTP(w, r)
		case LoginServiceSocialMediaLoginProcedure:
			loginServiceSocialMediaLoginHandler.ServeHTTP(w, r)
		case LoginServiceSignUpUsernameOrEmailProcedure:
			loginServiceSignUpUsernameOrEmailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLoginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLoginServiceHandler struct{}

func (UnimplementedLoginServiceHandler) Login(context.Context, *connect.Request[protos.LoginRequest]) (*connect.Response[protos.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.LoginService.Login is not implemented"))
}

func (UnimplementedLoginServiceHandler) SocialMediaLogin(context.Context, *connect.Request[protos.SocialMediaLoginRequest]) (*connect.Response[protos.SocialMediaLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.LoginService.SocialMediaLogin is not implemented"))
}

func (UnimplementedLoginServiceHandler) SignUpUsernameOrEmail(context.Context, *connect.Request[protos.SignUpUsernameOrEmailRequest]) (*connect.Response[protos.SignUpUsernameOrEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.LoginService.SignUpUsernameOrEmail is not implemented"))
}
