// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: player.proto

package protosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protos "sonic-trivia/backend/protos"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PlayerServiceName is the fully-qualified name of the PlayerService service.
	PlayerServiceName = "protos.PlayerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PlayerServiceCreatePlayerProcedure is the fully-qualified name of the PlayerService's
	// CreatePlayer RPC.
	PlayerServiceCreatePlayerProcedure = "/protos.PlayerService/CreatePlayer"
	// PlayerServiceGetPlayerProcedure is the fully-qualified name of the PlayerService's GetPlayer RPC.
	PlayerServiceGetPlayerProcedure = "/protos.PlayerService/GetPlayer"
	// PlayerServiceUpdatePlayerProcedure is the fully-qualified name of the PlayerService's
	// UpdatePlayer RPC.
	PlayerServiceUpdatePlayerProcedure = "/protos.PlayerService/UpdatePlayer"
	// PlayerServiceDeletePlayerProcedure is the fully-qualified name of the PlayerService's
	// DeletePlayer RPC.
	PlayerServiceDeletePlayerProcedure = "/protos.PlayerService/DeletePlayer"
	// PlayerServiceUpdateSonicCharacterProcedure is the fully-qualified name of the PlayerService's
	// UpdateSonicCharacter RPC.
	PlayerServiceUpdateSonicCharacterProcedure = "/protos.PlayerService/UpdateSonicCharacter"
	// PlayerServiceGetSonicCharactersProcedure is the fully-qualified name of the PlayerService's
	// GetSonicCharacters RPC.
	PlayerServiceGetSonicCharactersProcedure = "/protos.PlayerService/GetSonicCharacters"
	// PlayerServiceSelectCharacterProcedure is the fully-qualified name of the PlayerService's
	// SelectCharacter RPC.
	PlayerServiceSelectCharacterProcedure = "/protos.PlayerService/SelectCharacter"
)

// PlayerServiceClient is a client for the protos.PlayerService service.
type PlayerServiceClient interface {
	CreatePlayer(context.Context, *connect.Request[protos.Player]) (*connect.Response[protos.Player], error)
	GetPlayer(context.Context, *connect.Request[protos.GetPlayerRequest]) (*connect.Response[protos.GetPlayerResponse], error)
	UpdatePlayer(context.Context, *connect.Request[protos.Player]) (*connect.Response[protos.Player], error)
	DeletePlayer(context.Context, *connect.Request[protos.DeletePlayerRequest]) (*connect.Response[protos.DeletePlayerResponse], error)
	UpdateSonicCharacter(context.Context, *connect.Request[protos.SonicCharacter]) (*connect.Response[protos.SonicCharacter], error)
	GetSonicCharacters(context.Context, *connect.Request[protos.GetSonicCharactersRequest]) (*connect.Response[protos.GetSonicCharactersResponse], error)
	SelectCharacter(context.Context, *connect.Request[protos.SelectCharacterRequest]) (*connect.Response[protos.SelectCharacterResponse], error)
}

// NewPlayerServiceClient constructs a client for the protos.PlayerService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPlayerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PlayerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	playerServiceMethods := protos.File_player_proto.Services().ByName("PlayerService").Methods()
	return &playerServiceClient{
		createPlayer: connect.NewClient[protos.Player, protos.Player](
			httpClient,
			baseURL+PlayerServiceCreatePlayerProcedure,
			connect.WithSchema(playerServiceMethods.ByName("CreatePlayer")),
			connect.WithClientOptions(opts...),
		),
		getPlayer: connect.NewClient[protos.GetPlayerRequest, protos.GetPlayerResponse](
			httpClient,
			baseURL+PlayerServiceGetPlayerProcedure,
			connect.WithSchema(playerServiceMethods.ByName("GetPlayer")),
			connect.WithClientOptions(opts...),
		),
		updatePlayer: connect.NewClient[protos.Player, protos.Player](
			httpClient,
			baseURL+PlayerServiceUpdatePlayerProcedure,
			connect.WithSchema(playerServiceMethods.ByName("UpdatePlayer")),
			connect.WithClientOptions(opts...),
		),
		deletePlayer: connect.NewClient[protos.DeletePlayerRequest, protos.DeletePlayerResponse](
			httpClient,
			baseURL+PlayerServiceDeletePlayerProcedure,
			connect.WithSchema(playerServiceMethods.ByName("DeletePlayer")),
			connect.WithClientOptions(opts...),
		),
		updateSonicCharacter: connect.NewClient[protos.SonicCharacter, protos.SonicCharacter](
			httpClient,
			baseURL+PlayerServiceUpdateSonicCharacterProcedure,
			connect.WithSchema(playerServiceMethods.ByName("UpdateSonicCharacter")),
			connect.WithClientOptions(opts...),
		),
		getSonicCharacters: connect.NewClient[protos.GetSonicCharactersRequest, protos.GetSonicCharactersResponse](
			httpClient,
			baseURL+PlayerServiceGetSonicCharactersProcedure,
			connect.WithSchema(playerServiceMethods.ByName("GetSonicCharacters")),
			connect.WithClientOptions(opts...),
		),
		selectCharacter: connect.NewClient[protos.SelectCharacterRequest, protos.SelectCharacterResponse](
			httpClient,
			baseURL+PlayerServiceSelectCharacterProcedure,
			connect.WithSchema(playerServiceMethods.ByName("SelectCharacter")),
			connect.WithClientOptions(opts...),
		),
	}
}

// playerServiceClient implements PlayerServiceClient.
type playerServiceClient struct {
	createPlayer         *connect.Client[protos.Player, protos.Player]
	getPlayer            *connect.Client[protos.GetPlayerRequest, protos.GetPlayerResponse]
	updatePlayer         *connect.Client[protos.Player, protos.Player]
	deletePlayer         *connect.Client[protos.DeletePlayerRequest, protos.DeletePlayerResponse]
	updateSonicCharacter *connect.Client[protos.SonicCharacter, protos.SonicCharacter]
	getSonicCharacters   *connect.Client[protos.GetSonicCharactersRequest, protos.GetSonicCharactersResponse]
	selectCharacter      *connect.Client[protos.SelectCharacterRequest, protos.SelectCharacterResponse]
}

// CreatePlayer calls protos.PlayerService.CreatePlayer.
func (c *playerServiceClient) CreatePlayer(ctx context.Context, req *connect.Request[protos.Player]) (*connect.Response[protos.Player], error) {
	return c.createPlayer.CallUnary(ctx, req)
}

// GetPlayer calls protos.PlayerService.GetPlayer.
func (c *playerServiceClient) GetPlayer(ctx context.Context, req *connect.Request[protos.GetPlayerRequest]) (*connect.Response[protos.GetPlayerResponse], error) {
	return c.getPlayer.CallUnary(ctx, req)
}

// UpdatePlayer calls protos.PlayerService.UpdatePlayer.
func (c *playerServiceClient) UpdatePlayer(ctx context.Context, req *connect.Request[protos.Player]) (*connect.Response[protos.Player], error) {
	return c.updatePlayer.CallUnary(ctx, req)
}

// DeletePlayer calls protos.PlayerService.DeletePlayer.
func (c *playerServiceClient) DeletePlayer(ctx context.Context, req *connect.Request[protos.DeletePlayerRequest]) (*connect.Response[protos.DeletePlayerResponse], error) {
	return c.deletePlayer.CallUnary(ctx, req)
}

// UpdateSonicCharacter calls protos.PlayerService.UpdateSonicCharacter.
func (c *playerServiceClient) UpdateSonicCharacter(ctx context.Context, req *connect.Request[protos.SonicCharacter]) (*connect.Response[protos.SonicCharacter], error) {
	return c.updateSonicCharacter.CallUnary(ctx, req)
}

// GetSonicCharacters calls protos.PlayerService.GetSonicCharacters.
func (c *playerServiceClient) GetSonicCharacters(ctx context.Context, req *connect.Request[protos.GetSonicCharactersRequest]) (*connect.Response[protos.GetSonicCharactersResponse], error) {
	return c.getSonicCharacters.CallUnary(ctx, req)
}

// SelectCharacter calls protos.PlayerService.SelectCharacter.
func (c *playerServiceClient) SelectCharacter(ctx context.Context, req *connect.Request[protos.SelectCharacterRequest]) (*connect.Response[protos.SelectCharacterResponse], error) {
	return c.selectCharacter.CallUnary(ctx, req)
}

// PlayerServiceHandler is an implementation of the protos.PlayerService service.
type PlayerServiceHandler interface {
	CreatePlayer(context.Context, *connect.Request[protos.Player]) (*connect.Response[protos.Player], error)
	GetPlayer(context.Context, *connect.Request[protos.GetPlayerRequest]) (*connect.Response[protos.GetPlayerResponse], error)
	UpdatePlayer(context.Context, *connect.Request[protos.Player]) (*connect.Response[protos.Player], error)
	DeletePlayer(context.Context, *connect.Request[protos.DeletePlayerRequest]) (*connect.Response[protos.DeletePlayerResponse], error)
	UpdateSonicCharacter(context.Context, *connect.Request[protos.SonicCharacter]) (*connect.Response[protos.SonicCharacter], error)
	GetSonicCharacters(context.Context, *connect.Request[protos.GetSonicCharactersRequest]) (*connect.Response[protos.GetSonicCharactersResponse], error)
	SelectCharacter(context.Context, *connect.Request[protos.SelectCharacterRequest]) (*connect.Response[protos.SelectCharacterResponse], error)
}

// NewPlayerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPlayerServiceHandler(svc PlayerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	playerServiceMethods := protos.File_player_proto.Services().ByName("PlayerService").Methods()
	playerServiceCreatePlayerHandler := connect.NewUnaryHandler(
		PlayerServiceCreatePlayerProcedure,
		svc.CreatePlayer,
		connect.WithSchema(playerServiceMethods.ByName("CreatePlayer")),
		connect.WithHandlerOptions(opts...),
	)
	playerServiceGetPlayerHandler := connect.NewUnaryHandler(
		PlayerServiceGetPlayerProcedure,
		svc.GetPlayer,
		connect.WithSchema(playerServiceMethods.ByName("GetPlayer")),
		connect.WithHandlerOptions(opts...),
	)
	playerServiceUpdatePlayerHandler := connect.NewUnaryHandler(
		PlayerServiceUpdatePlayerProcedure,
		svc.UpdatePlayer,
		connect.WithSchema(playerServiceMethods.ByName("UpdatePlayer")),
		connect.WithHandlerOptions(opts...),
	)
	playerServiceDeletePlayerHandler := connect.NewUnaryHandler(
		PlayerServiceDeletePlayerProcedure,
		svc.DeletePlayer,
		connect.WithSchema(playerServiceMethods.ByName("DeletePlayer")),
		connect.WithHandlerOptions(opts...),
	)
	playerServiceUpdateSonicCharacterHandler := connect.NewUnaryHandler(
		PlayerServiceUpdateSonicCharacterProcedure,
		svc.UpdateSonicCharacter,
		connect.WithSchema(playerServiceMethods.ByName("UpdateSonicCharacter")),
		connect.WithHandlerOptions(opts...),
	)
	playerServiceGetSonicCharactersHandler := connect.NewUnaryHandler(
		PlayerServiceGetSonicCharactersProcedure,
		svc.GetSonicCharacters,
		connect.WithSchema(playerServiceMethods.ByName("GetSonicCharacters")),
		connect.WithHandlerOptions(opts...),
	)
	playerServiceSelectCharacterHandler := connect.NewUnaryHandler(
		PlayerServiceSelectCharacterProcedure,
		svc.SelectCharacter,
		connect.WithSchema(playerServiceMethods.ByName("SelectCharacter")),
		connect.WithHandlerOptions(opts...),
	)
	return "/protos.PlayerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PlayerServiceCreatePlayerProcedure:
			playerServiceCreatePlayerHandler.ServeHTTP(w, r)
		case PlayerServiceGetPlayerProcedure:
			playerServiceGetPlayerHandler.ServeHTTP(w, r)
		case PlayerServiceUpdatePlayerProcedure:
			playerServiceUpdatePlayerHandler.ServeHTTP(w, r)
		case PlayerServiceDeletePlayerProcedure:
			playerServiceDeletePlayerHandler.ServeHTTP(w, r)
		case PlayerServiceUpdateSonicCharacterProcedure:
			playerServiceUpdateSonicCharacterHandler.ServeHTTP(w, r)
		case PlayerServiceGetSonicCharactersProcedure:
			playerServiceGetSonicCharactersHandler.ServeHTTP(w, r)
		case PlayerServiceSelectCharacterProcedure:
			playerServiceSelectCharacterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPlayerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPlayerServiceHandler struct{}

func (UnimplementedPlayerServiceHandler) CreatePlayer(context.Context, *connect.Request[protos.Player]) (*connect.Response[protos.Player], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.PlayerService.CreatePlayer is not implemented"))
}

func (UnimplementedPlayerServiceHandler) GetPlayer(context.Context, *connect.Request[protos.GetPlayerRequest]) (*connect.Response[protos.GetPlayerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.PlayerService.GetPlayer is not implemented"))
}

func (UnimplementedPlayerServiceHandler) UpdatePlayer(context.Context, *connect.Request[protos.Player]) (*connect.Response[protos.Player], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.PlayerService.UpdatePlayer is not implemented"))
}

func (UnimplementedPlayerServiceHandler) DeletePlayer(context.Context, *connect.Request[protos.DeletePlayerRequest]) (*connect.Response[protos.DeletePlayerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.PlayerService.DeletePlayer is not implemented"))
}

func (UnimplementedPlayerServiceHandler) UpdateSonicCharacter(context.Context, *connect.Request[protos.SonicCharacter]) (*connect.Response[protos.SonicCharacter], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.PlayerService.UpdateSonicCharacter is not implemented"))
}

func (UnimplementedPlayerServiceHandler) GetSonicCharacters(context.Context, *connect.Request[protos.GetSonicCharactersRequest]) (*connect.Response[protos.GetSonicCharactersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.PlayerService.GetSonicCharacters is not implemented"))
}

func (UnimplementedPlayerServiceHandler) SelectCharacter(context.Context, *connect.Request[protos.SelectCharacterRequest]) (*connect.Response[protos.SelectCharacterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.PlayerService.SelectCharacter is not implemented"))
}
