// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: trivia.proto

package protosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protos "sonic-trivia/backend/protos"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TriviaServiceName is the fully-qualified name of the TriviaService service.
	TriviaServiceName = "protos.TriviaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TriviaServiceGetQuestionProcedure is the fully-qualified name of the TriviaService's GetQuestion
	// RPC.
	TriviaServiceGetQuestionProcedure = "/protos.TriviaService/GetQuestion"
	// TriviaServiceGetRandomQuestionsProcedure is the fully-qualified name of the TriviaService's
	// GetRandomQuestions RPC.
	TriviaServiceGetRandomQuestionsProcedure = "/protos.TriviaService/GetRandomQuestions"
	// TriviaServiceUpdateQuestionProcedure is the fully-qualified name of the TriviaService's
	// UpdateQuestion RPC.
	TriviaServiceUpdateQuestionProcedure = "/protos.TriviaService/UpdateQuestion"
	// TriviaServiceDeleteQuestionProcedure is the fully-qualified name of the TriviaService's
	// DeleteQuestion RPC.
	TriviaServiceDeleteQuestionProcedure = "/protos.TriviaService/DeleteQuestion"
	// TriviaServiceCreateQuestionProcedure is the fully-qualified name of the TriviaService's
	// CreateQuestion RPC.
	TriviaServiceCreateQuestionProcedure = "/protos.TriviaService/CreateQuestion"
	// TriviaServiceGetAnsweredQuestionsProcedure is the fully-qualified name of the TriviaService's
	// GetAnsweredQuestions RPC.
	TriviaServiceGetAnsweredQuestionsProcedure = "/protos.TriviaService/GetAnsweredQuestions"
	// TriviaServiceCheckAnswerProcedure is the fully-qualified name of the TriviaService's CheckAnswer
	// RPC.
	TriviaServiceCheckAnswerProcedure = "/protos.TriviaService/CheckAnswer"
	// TriviaServiceCreateQuestionCollectionProcedure is the fully-qualified name of the TriviaService's
	// CreateQuestionCollection RPC.
	TriviaServiceCreateQuestionCollectionProcedure = "/protos.TriviaService/CreateQuestionCollection"
	// TriviaServiceDeleteQuestionCollectionProcedure is the fully-qualified name of the TriviaService's
	// DeleteQuestionCollection RPC.
	TriviaServiceDeleteQuestionCollectionProcedure = "/protos.TriviaService/DeleteQuestionCollection"
	// TriviaServiceUpdateQuestionCollectionProcedure is the fully-qualified name of the TriviaService's
	// UpdateQuestionCollection RPC.
	TriviaServiceUpdateQuestionCollectionProcedure = "/protos.TriviaService/UpdateQuestionCollection"
	// TriviaServiceGetQuestionCollectionsProcedure is the fully-qualified name of the TriviaService's
	// GetQuestionCollections RPC.
	TriviaServiceGetQuestionCollectionsProcedure = "/protos.TriviaService/GetQuestionCollections"
)

// TriviaServiceClient is a client for the protos.TriviaService service.
type TriviaServiceClient interface {
	GetQuestion(context.Context, *connect.Request[protos.GetQuestionRequest]) (*connect.Response[protos.GetQuestionResponse], error)
	GetRandomQuestions(context.Context, *connect.Request[protos.GetRandomQuestionsRequest]) (*connect.Response[protos.GetRandomQuestionsResponse], error)
	UpdateQuestion(context.Context, *connect.Request[protos.UpdateQuestionRequest]) (*connect.Response[protos.UpdateQuestionResponse], error)
	DeleteQuestion(context.Context, *connect.Request[protos.DeleteQuestionRequest]) (*connect.Response[protos.DeleteQuestionResponse], error)
	CreateQuestion(context.Context, *connect.Request[protos.CreateQuestionRequest]) (*connect.Response[protos.CreateQuestionResponse], error)
	GetAnsweredQuestions(context.Context, *connect.Request[protos.GetAnsweredQuestionsRequest]) (*connect.Response[protos.GetAnsweredQuestionsResponse], error)
	CheckAnswer(context.Context, *connect.Request[protos.CheckAnswerRequest]) (*connect.Response[protos.CheckAnswerResponse], error)
	CreateQuestionCollection(context.Context, *connect.Request[protos.CreateQuestionCollectionRequest]) (*connect.Response[protos.CreateQuestionCollectionResponse], error)
	DeleteQuestionCollection(context.Context, *connect.Request[protos.DeleteQuestionCollectionRequest]) (*connect.Response[protos.DeleteQuestionCollectionResponse], error)
	UpdateQuestionCollection(context.Context, *connect.Request[protos.UpdateQuestionCollectionRequest]) (*connect.Response[protos.UpdateQuestionCollectionResponse], error)
	GetQuestionCollections(context.Context, *connect.Request[protos.GetQuestionCollectionsRequest]) (*connect.Response[protos.GetQuestionCollectionsResponse], error)
}

// NewTriviaServiceClient constructs a client for the protos.TriviaService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTriviaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TriviaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	triviaServiceMethods := protos.File_trivia_proto.Services().ByName("TriviaService").Methods()
	return &triviaServiceClient{
		getQuestion: connect.NewClient[protos.GetQuestionRequest, protos.GetQuestionResponse](
			httpClient,
			baseURL+TriviaServiceGetQuestionProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("GetQuestion")),
			connect.WithClientOptions(opts...),
		),
		getRandomQuestions: connect.NewClient[protos.GetRandomQuestionsRequest, protos.GetRandomQuestionsResponse](
			httpClient,
			baseURL+TriviaServiceGetRandomQuestionsProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("GetRandomQuestions")),
			connect.WithClientOptions(opts...),
		),
		updateQuestion: connect.NewClient[protos.UpdateQuestionRequest, protos.UpdateQuestionResponse](
			httpClient,
			baseURL+TriviaServiceUpdateQuestionProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("UpdateQuestion")),
			connect.WithClientOptions(opts...),
		),
		deleteQuestion: connect.NewClient[protos.DeleteQuestionRequest, protos.DeleteQuestionResponse](
			httpClient,
			baseURL+TriviaServiceDeleteQuestionProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("DeleteQuestion")),
			connect.WithClientOptions(opts...),
		),
		createQuestion: connect.NewClient[protos.CreateQuestionRequest, protos.CreateQuestionResponse](
			httpClient,
			baseURL+TriviaServiceCreateQuestionProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("CreateQuestion")),
			connect.WithClientOptions(opts...),
		),
		getAnsweredQuestions: connect.NewClient[protos.GetAnsweredQuestionsRequest, protos.GetAnsweredQuestionsResponse](
			httpClient,
			baseURL+TriviaServiceGetAnsweredQuestionsProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("GetAnsweredQuestions")),
			connect.WithClientOptions(opts...),
		),
		checkAnswer: connect.NewClient[protos.CheckAnswerRequest, protos.CheckAnswerResponse](
			httpClient,
			baseURL+TriviaServiceCheckAnswerProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("CheckAnswer")),
			connect.WithClientOptions(opts...),
		),
		createQuestionCollection: connect.NewClient[protos.CreateQuestionCollectionRequest, protos.CreateQuestionCollectionResponse](
			httpClient,
			baseURL+TriviaServiceCreateQuestionCollectionProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("CreateQuestionCollection")),
			connect.WithClientOptions(opts...),
		),
		deleteQuestionCollection: connect.NewClient[protos.DeleteQuestionCollectionRequest, protos.DeleteQuestionCollectionResponse](
			httpClient,
			baseURL+TriviaServiceDeleteQuestionCollectionProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("DeleteQuestionCollection")),
			connect.WithClientOptions(opts...),
		),
		updateQuestionCollection: connect.NewClient[protos.UpdateQuestionCollectionRequest, protos.UpdateQuestionCollectionResponse](
			httpClient,
			baseURL+TriviaServiceUpdateQuestionCollectionProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("UpdateQuestionCollection")),
			connect.WithClientOptions(opts...),
		),
		getQuestionCollections: connect.NewClient[protos.GetQuestionCollectionsRequest, protos.GetQuestionCollectionsResponse](
			httpClient,
			baseURL+TriviaServiceGetQuestionCollectionsProcedure,
			connect.WithSchema(triviaServiceMethods.ByName("GetQuestionCollections")),
			connect.WithClientOptions(opts...),
		),
	}
}

// triviaServiceClient implements TriviaServiceClient.
type triviaServiceClient struct {
	getQuestion              *connect.Client[protos.GetQuestionRequest, protos.GetQuestionResponse]
	getRandomQuestions       *connect.Client[protos.GetRandomQuestionsRequest, protos.GetRandomQuestionsResponse]
	updateQuestion           *connect.Client[protos.UpdateQuestionRequest, protos.UpdateQuestionResponse]
	deleteQuestion           *connect.Client[protos.DeleteQuestionRequest, protos.DeleteQuestionResponse]
	createQuestion           *connect.Client[protos.CreateQuestionRequest, protos.CreateQuestionResponse]
	getAnsweredQuestions     *connect.Client[protos.GetAnsweredQuestionsRequest, protos.GetAnsweredQuestionsResponse]
	checkAnswer              *connect.Client[protos.CheckAnswerRequest, protos.CheckAnswerResponse]
	createQuestionCollection *connect.Client[protos.CreateQuestionCollectionRequest, protos.CreateQuestionCollectionResponse]
	deleteQuestionCollection *connect.Client[protos.DeleteQuestionCollectionRequest, protos.DeleteQuestionCollectionResponse]
	updateQuestionCollection *connect.Client[protos.UpdateQuestionCollectionRequest, protos.UpdateQuestionCollectionResponse]
	getQuestionCollections   *connect.Client[protos.GetQuestionCollectionsRequest, protos.GetQuestionCollectionsResponse]
}

// GetQuestion calls protos.TriviaService.GetQuestion.
func (c *triviaServiceClient) GetQuestion(ctx context.Context, req *connect.Request[protos.GetQuestionRequest]) (*connect.Response[protos.GetQuestionResponse], error) {
	return c.getQuestion.CallUnary(ctx, req)
}

// GetRandomQuestions calls protos.TriviaService.GetRandomQuestions.
func (c *triviaServiceClient) GetRandomQuestions(ctx context.Context, req *connect.Request[protos.GetRandomQuestionsRequest]) (*connect.Response[protos.GetRandomQuestionsResponse], error) {
	return c.getRandomQuestions.CallUnary(ctx, req)
}

// UpdateQuestion calls protos.TriviaService.UpdateQuestion.
func (c *triviaServiceClient) UpdateQuestion(ctx context.Context, req *connect.Request[protos.UpdateQuestionRequest]) (*connect.Response[protos.UpdateQuestionResponse], error) {
	return c.updateQuestion.CallUnary(ctx, req)
}

// DeleteQuestion calls protos.TriviaService.DeleteQuestion.
func (c *triviaServiceClient) DeleteQuestion(ctx context.Context, req *connect.Request[protos.DeleteQuestionRequest]) (*connect.Response[protos.DeleteQuestionResponse], error) {
	return c.deleteQuestion.CallUnary(ctx, req)
}

// CreateQuestion calls protos.TriviaService.CreateQuestion.
func (c *triviaServiceClient) CreateQuestion(ctx context.Context, req *connect.Request[protos.CreateQuestionRequest]) (*connect.Response[protos.CreateQuestionResponse], error) {
	return c.createQuestion.CallUnary(ctx, req)
}

// GetAnsweredQuestions calls protos.TriviaService.GetAnsweredQuestions.
func (c *triviaServiceClient) GetAnsweredQuestions(ctx context.Context, req *connect.Request[protos.GetAnsweredQuestionsRequest]) (*connect.Response[protos.GetAnsweredQuestionsResponse], error) {
	return c.getAnsweredQuestions.CallUnary(ctx, req)
}

// CheckAnswer calls protos.TriviaService.CheckAnswer.
func (c *triviaServiceClient) CheckAnswer(ctx context.Context, req *connect.Request[protos.CheckAnswerRequest]) (*connect.Response[protos.CheckAnswerResponse], error) {
	return c.checkAnswer.CallUnary(ctx, req)
}

// CreateQuestionCollection calls protos.TriviaService.CreateQuestionCollection.
func (c *triviaServiceClient) CreateQuestionCollection(ctx context.Context, req *connect.Request[protos.CreateQuestionCollectionRequest]) (*connect.Response[protos.CreateQuestionCollectionResponse], error) {
	return c.createQuestionCollection.CallUnary(ctx, req)
}

// DeleteQuestionCollection calls protos.TriviaService.DeleteQuestionCollection.
func (c *triviaServiceClient) DeleteQuestionCollection(ctx context.Context, req *connect.Request[protos.DeleteQuestionCollectionRequest]) (*connect.Response[protos.DeleteQuestionCollectionResponse], error) {
	return c.deleteQuestionCollection.CallUnary(ctx, req)
}

// UpdateQuestionCollection calls protos.TriviaService.UpdateQuestionCollection.
func (c *triviaServiceClient) UpdateQuestionCollection(ctx context.Context, req *connect.Request[protos.UpdateQuestionCollectionRequest]) (*connect.Response[protos.UpdateQuestionCollectionResponse], error) {
	return c.updateQuestionCollection.CallUnary(ctx, req)
}

// GetQuestionCollections calls protos.TriviaService.GetQuestionCollections.
func (c *triviaServiceClient) GetQuestionCollections(ctx context.Context, req *connect.Request[protos.GetQuestionCollectionsRequest]) (*connect.Response[protos.GetQuestionCollectionsResponse], error) {
	return c.getQuestionCollections.CallUnary(ctx, req)
}

// TriviaServiceHandler is an implementation of the protos.TriviaService service.
type TriviaServiceHandler interface {
	GetQuestion(context.Context, *connect.Request[protos.GetQuestionRequest]) (*connect.Response[protos.GetQuestionResponse], error)
	GetRandomQuestions(context.Context, *connect.Request[protos.GetRandomQuestionsRequest]) (*connect.Response[protos.GetRandomQuestionsResponse], error)
	UpdateQuestion(context.Context, *connect.Request[protos.UpdateQuestionRequest]) (*connect.Response[protos.UpdateQuestionResponse], error)
	DeleteQuestion(context.Context, *connect.Request[protos.DeleteQuestionRequest]) (*connect.Response[protos.DeleteQuestionResponse], error)
	CreateQuestion(context.Context, *connect.Request[protos.CreateQuestionRequest]) (*connect.Response[protos.CreateQuestionResponse], error)
	GetAnsweredQuestions(context.Context, *connect.Request[protos.GetAnsweredQuestionsRequest]) (*connect.Response[protos.GetAnsweredQuestionsResponse], error)
	CheckAnswer(context.Context, *connect.Request[protos.CheckAnswerRequest]) (*connect.Response[protos.CheckAnswerResponse], error)
	CreateQuestionCollection(context.Context, *connect.Request[protos.CreateQuestionCollectionRequest]) (*connect.Response[protos.CreateQuestionCollectionResponse], error)
	DeleteQuestionCollection(context.Context, *connect.Request[protos.DeleteQuestionCollectionRequest]) (*connect.Response[protos.DeleteQuestionCollectionResponse], error)
	UpdateQuestionCollection(context.Context, *connect.Request[protos.UpdateQuestionCollectionRequest]) (*connect.Response[protos.UpdateQuestionCollectionResponse], error)
	GetQuestionCollections(context.Context, *connect.Request[protos.GetQuestionCollectionsRequest]) (*connect.Response[protos.GetQuestionCollectionsResponse], error)
}

// NewTriviaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTriviaServiceHandler(svc TriviaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	triviaServiceMethods := protos.File_trivia_proto.Services().ByName("TriviaService").Methods()
	triviaServiceGetQuestionHandler := connect.NewUnaryHandler(
		TriviaServiceGetQuestionProcedure,
		svc.GetQuestion,
		connect.WithSchema(triviaServiceMethods.ByName("GetQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceGetRandomQuestionsHandler := connect.NewUnaryHandler(
		TriviaServiceGetRandomQuestionsProcedure,
		svc.GetRandomQuestions,
		connect.WithSchema(triviaServiceMethods.ByName("GetRandomQuestions")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceUpdateQuestionHandler := connect.NewUnaryHandler(
		TriviaServiceUpdateQuestionProcedure,
		svc.UpdateQuestion,
		connect.WithSchema(triviaServiceMethods.ByName("UpdateQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceDeleteQuestionHandler := connect.NewUnaryHandler(
		TriviaServiceDeleteQuestionProcedure,
		svc.DeleteQuestion,
		connect.WithSchema(triviaServiceMethods.ByName("DeleteQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceCreateQuestionHandler := connect.NewUnaryHandler(
		TriviaServiceCreateQuestionProcedure,
		svc.CreateQuestion,
		connect.WithSchema(triviaServiceMethods.ByName("CreateQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceGetAnsweredQuestionsHandler := connect.NewUnaryHandler(
		TriviaServiceGetAnsweredQuestionsProcedure,
		svc.GetAnsweredQuestions,
		connect.WithSchema(triviaServiceMethods.ByName("GetAnsweredQuestions")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceCheckAnswerHandler := connect.NewUnaryHandler(
		TriviaServiceCheckAnswerProcedure,
		svc.CheckAnswer,
		connect.WithSchema(triviaServiceMethods.ByName("CheckAnswer")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceCreateQuestionCollectionHandler := connect.NewUnaryHandler(
		TriviaServiceCreateQuestionCollectionProcedure,
		svc.CreateQuestionCollection,
		connect.WithSchema(triviaServiceMethods.ByName("CreateQuestionCollection")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceDeleteQuestionCollectionHandler := connect.NewUnaryHandler(
		TriviaServiceDeleteQuestionCollectionProcedure,
		svc.DeleteQuestionCollection,
		connect.WithSchema(triviaServiceMethods.ByName("DeleteQuestionCollection")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceUpdateQuestionCollectionHandler := connect.NewUnaryHandler(
		TriviaServiceUpdateQuestionCollectionProcedure,
		svc.UpdateQuestionCollection,
		connect.WithSchema(triviaServiceMethods.ByName("UpdateQuestionCollection")),
		connect.WithHandlerOptions(opts...),
	)
	triviaServiceGetQuestionCollectionsHandler := connect.NewUnaryHandler(
		TriviaServiceGetQuestionCollectionsProcedure,
		svc.GetQuestionCollections,
		connect.WithSchema(triviaServiceMethods.ByName("GetQuestionCollections")),
		connect.WithHandlerOptions(opts...),
	)
	return "/protos.TriviaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TriviaServiceGetQuestionProcedure:
			triviaServiceGetQuestionHandler.ServeHTTP(w, r)
		case TriviaServiceGetRandomQuestionsProcedure:
			triviaServiceGetRandomQuestionsHandler.ServeHTTP(w, r)
		case TriviaServiceUpdateQuestionProcedure:
			triviaServiceUpdateQuestionHandler.ServeHTTP(w, r)
		case TriviaServiceDeleteQuestionProcedure:
			triviaServiceDeleteQuestionHandler.ServeHTTP(w, r)
		case TriviaServiceCreateQuestionProcedure:
			triviaServiceCreateQuestionHandler.ServeHTTP(w, r)
		case TriviaServiceGetAnsweredQuestionsProcedure:
			triviaServiceGetAnsweredQuestionsHandler.ServeHTTP(w, r)
		case TriviaServiceCheckAnswerProcedure:
			triviaServiceCheckAnswerHandler.ServeHTTP(w, r)
		case TriviaServiceCreateQuestionCollectionProcedure:
			triviaServiceCreateQuestionCollectionHandler.ServeHTTP(w, r)
		case TriviaServiceDeleteQuestionCollectionProcedure:
			triviaServiceDeleteQuestionCollectionHandler.ServeHTTP(w, r)
		case TriviaServiceUpdateQuestionCollectionProcedure:
			triviaServiceUpdateQuestionCollectionHandler.ServeHTTP(w, r)
		case TriviaServiceGetQuestionCollectionsProcedure:
			triviaServiceGetQuestionCollectionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTriviaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTriviaServiceHandler struct{}

func (UnimplementedTriviaServiceHandler) GetQuestion(context.Context, *connect.Request[protos.GetQuestionRequest]) (*connect.Response[protos.GetQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.GetQuestion is not implemented"))
}

func (UnimplementedTriviaServiceHandler) GetRandomQuestions(context.Context, *connect.Request[protos.GetRandomQuestionsRequest]) (*connect.Response[protos.GetRandomQuestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.GetRandomQuestions is not implemented"))
}

func (UnimplementedTriviaServiceHandler) UpdateQuestion(context.Context, *connect.Request[protos.UpdateQuestionRequest]) (*connect.Response[protos.UpdateQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.UpdateQuestion is not implemented"))
}

func (UnimplementedTriviaServiceHandler) DeleteQuestion(context.Context, *connect.Request[protos.DeleteQuestionRequest]) (*connect.Response[protos.DeleteQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.DeleteQuestion is not implemented"))
}

func (UnimplementedTriviaServiceHandler) CreateQuestion(context.Context, *connect.Request[protos.CreateQuestionRequest]) (*connect.Response[protos.CreateQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.CreateQuestion is not implemented"))
}

func (UnimplementedTriviaServiceHandler) GetAnsweredQuestions(context.Context, *connect.Request[protos.GetAnsweredQuestionsRequest]) (*connect.Response[protos.GetAnsweredQuestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.GetAnsweredQuestions is not implemented"))
}

func (UnimplementedTriviaServiceHandler) CheckAnswer(context.Context, *connect.Request[protos.CheckAnswerRequest]) (*connect.Response[protos.CheckAnswerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.CheckAnswer is not implemented"))
}

func (UnimplementedTriviaServiceHandler) CreateQuestionCollection(context.Context, *connect.Request[protos.CreateQuestionCollectionRequest]) (*connect.Response[protos.CreateQuestionCollectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.CreateQuestionCollection is not implemented"))
}

func (UnimplementedTriviaServiceHandler) DeleteQuestionCollection(context.Context, *connect.Request[protos.DeleteQuestionCollectionRequest]) (*connect.Response[protos.DeleteQuestionCollectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.DeleteQuestionCollection is not implemented"))
}

func (UnimplementedTriviaServiceHandler) UpdateQuestionCollection(context.Context, *connect.Request[protos.UpdateQuestionCollectionRequest]) (*connect.Response[protos.UpdateQuestionCollectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.UpdateQuestionCollection is not implemented"))
}

func (UnimplementedTriviaServiceHandler) GetQuestionCollections(context.Context, *connect.Request[protos.GetQuestionCollectionsRequest]) (*connect.Response[protos.GetQuestionCollectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.TriviaService.GetQuestionCollections is not implemented"))
}
