syntax = "proto3";

package protos;

option go_package = "sonic-trivia/backend/protos";

enum IndividualGameModes {
  INDIVIDUAL_GAME_MODES_UNSPECIFIED = 0;
  INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_TRIVIA = 1;
  INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_GUESS_THAT_SONG = 2;
  INDIVIDUAL_GAME_MODES_MULTIPLAYER_GUESS_THAT_SONG = 3;
  INDIVIDUAL_GAME_MODES_MULTIPLAYER_TRIVIA = 4;
}

enum TriviaCategories {
  TRIVIA_CATEGORIES_TRIVIA_CATEGORY_UNSPECIFIED = 0;
  TRIVIA_CATEGORIES_SONIC_ADVENTURES_1_TRIVIA = 2;
  TRIVIA_CATEGORIES_SONIC_ADVENTURES_2_TRIVIA = 1;
  TRIVIA_CATEGORIES_SONIC_HEROES_TRIVIA = 3;
}

enum GuessThatSongCategories {
  GUESS_THAT_SONG_CATEGORIES_GUESS_THAT_SONG_CATEGORY_UNSPECIFIED = 0;
  GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_1_GUESS_THAT_SONG = 2;
  GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_2_GUESS_THAT_SONG = 1;
  GUESS_THAT_SONG_CATEGORIES_SONIC_HEROES_GUESS_THAT_SONG = 3;
}
