syntax = "proto3";

package protos;

option go_package = "sonic-trivia/backend/protos";

message SongHint {
  string id = 1;
  string text = 2;
}

message Song {
  string id = 1;
  string song_title = 2;
  string artist = 3;
  string album = 4;
  string release_year = 5;
  string category = 6;
  string difficulty = 7;
  int32 plays_per_round = 8;
  int32 clip_duration = 9;
  string audio_url = 10;
  repeated SongHint hints = 11;
  optional string picture_url = 12;
  bool is_under_review = 13;
}

service GuessThatSongService {
  rpc CreateSong(CreateSongRequest) returns (CreateSongResponse) {}
  rpc GetSong(GetSongRequest) returns (GetSongResponse) {}
  rpc GetRandomSong(GetRandomSongRequest) returns (GetRandomSongResponse) {}
  rpc GetRandomSongs(GetRandomSongsRequest) returns (GetRandomSongsResponse) {}
  rpc UpdateSong(UpdateSongRequest) returns (UpdateSongResponse) {}
  rpc DeleteSong(DeleteSongRequest) returns (DeleteSongResponse) {}
  rpc SearchSong(SearchSongRequest) returns (SearchSongResponse) {}
  rpc CreateSongCollection(CreateSongCollectionRequest) returns (CreateSongCollectionResponse) {}
  rpc DeleteSongCollection(DeleteSongCollectionRequest) returns (DeleteSongCollectionResponse) {}
  rpc UpdateSongCollection(UpdateSongCollectionRequest) returns (UpdateSongCollectionResponse) {}
  rpc GetSongCollections(GetSongCollectionsRequest) returns (GetSongCollectionsResponse) {}
}

message GetSongCollectionsRequest {
  string user_id = 1;
  int32 page = 2;
  int32 page_size = 3;
}

message GetSongCollectionsResponse {
  repeated SongCollection collections = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

message SongCollection {
  string id = 1;
  string name = 2;
  string description = 3;
  string created_by = 4;
  repeated Song songs = 5;
  bool is_under_review = 6;
}

message UpdateSongCollectionRequest {
  string id = 1;
  string name = 2;
  string description = 3;
  repeated string song_ids = 4;
}

message UpdateSongCollectionResponse {
  bool is_success = 1;
}

message CreateSongCollectionRequest {
  string name = 1;
  string description = 2;
  string created_by = 3;
  string size_of_collection = 4;
  repeated string song_ids = 5;
}

message CreateSongCollectionResponse {
  string id = 1;
}

message DeleteSongCollectionRequest {
  string id = 1;
}

message DeleteSongCollectionResponse {
  bool is_success = 1;
}

message CreateSongsRequest {
  repeated Song songs = 1;
}

message CreateSongsResponse {
  bool is_success = 1;
}

message GetRandomSongsRequest {
  string category = 1;
  int32 how_many_rounds = 2;
  string difficulty = 3;
}

message GetRandomSongsResponse {
  repeated Song songs = 1;
}

message CreateSongRequest {
  Song song = 1;
  optional string collection_id = 2;
}

message CreateSongResponse {
  Song song = 1;
}

message GetSongRequest {
  string id = 1;
}

message GetSongResponse {
  Song song = 1;
}

message GetRandomSongRequest {
  string category = 1;
}

message GetRandomSongResponse {
  Song song = 1;
}

message UpdateSongRequest {
  Song song = 1;
  optional string collection_id = 2;
}

message UpdateSongResponse {
  Song song = 1;
}

message DeleteSongRequest {
  string id = 1;
}

message DeleteSongResponse {
  bool success = 1;
}

message SearchSongRequest {
  string query = 1;
}

message SearchSongResponse {
  repeated Song songs = 1;
}
