syntax = "proto3";

package protos;

import "google/protobuf/timestamp.proto";

option go_package = "sonic-trivia/backend/protos";

enum CharacterRarity {
  CHARACTER_RARITY_UNSPECIFIED = 0;
  CHARACTER_RARITY_COMMON = 1;
  CHARACTER_RARITY_RARE = 2;
  CHARACTER_RARITY_EPIC = 3;
  CHARACTER_RARITY_LEGENDARY = 4;
}

message Ability {
  string name = 1;
  string description = 2;
}

message SonicCharacter {
  string id = 1;
  string name = 2;
  string description = 3;
  string profile_picture = 4;
  repeated Ability abilities = 5;
  int32 speed = 6;
  int32 power = 7;
  int32 technique = 8;
  CharacterRarity rarity = 9;
  string game = 10;
  string quote = 11;
  string color = 12;
  bool unlocked = 13;
  google.protobuf.Timestamp unlocked_at = 14;
  google.protobuf.Timestamp last_used = 15;
  int64 games_played_with = 16;
}
message FriendList {
  string username = 1;
}
message Player {
  string name = 1;
  string email = 3;
  string socials_linked = 4;
  repeated SonicCharacter unlocked_characters = 5;
  string selected_character_id = 6;
  int64 total_points = 7;
  int64 total_successful_answers = 8;
  int64 total_answers = 9;
  string role = 10;
  int64 total_rings = 11;
  repeated FriendList friends = 12;
}

service PlayerService {
  rpc CreatePlayer(Player) returns (Player) {}
  rpc GetPlayer(GetPlayerRequest) returns (GetPlayerResponse) {}
  rpc UpdatePlayer(Player) returns (Player) {}
  rpc DeletePlayer(DeletePlayerRequest) returns (DeletePlayerResponse) {}
  rpc UpdateSonicCharacter(SonicCharacter) returns (SonicCharacter) {}
  rpc GetSonicCharacters(GetSonicCharactersRequest) returns (GetSonicCharactersResponse) {}
  rpc SelectCharacter(SelectCharacterRequest) returns (SelectCharacterResponse) {}
}
message GetPlayerRequest {
  string id = 1;
}
message GetPlayerResponse {
  Player player = 1;
}

message GetSonicCharactersRequest {
  string user_id = 1;
}
message GetSonicCharactersResponse {
  repeated SonicCharacter characters = 1;
}

message DeletePlayerRequest {
  string id = 1;
}
message DeletePlayerResponse {
  string message = 1;
}

message SelectCharacterRequest {
  string player_id = 1;
  string character_id = 2;
}

message SelectCharacterResponse {
  Player player = 1;
  string message = 2;
}
