// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: approvalqueue.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamApprovalQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamApprovalQueueRequest) Reset() {
	*x = StreamApprovalQueueRequest{}
	mi := &file_approvalqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamApprovalQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamApprovalQueueRequest) ProtoMessage() {}

func (x *StreamApprovalQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamApprovalQueueRequest.ProtoReflect.Descriptor instead.
func (*StreamApprovalQueueRequest) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{0}
}

type ApprovalQueueUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "added", "updated", "approved", "removed"
	ApprovalRequest *ApprovalRequest       `protobuf:"bytes,2,opt,name=approval_request,json=approvalRequest,proto3" json:"approval_request,omitempty"`
	Timestamp       string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApprovalQueueUpdate) Reset() {
	*x = ApprovalQueueUpdate{}
	mi := &file_approvalqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalQueueUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalQueueUpdate) ProtoMessage() {}

func (x *ApprovalQueueUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalQueueUpdate.ProtoReflect.Descriptor instead.
func (*ApprovalQueueUpdate) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalQueueUpdate) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ApprovalQueueUpdate) GetApprovalRequest() *ApprovalRequest {
	if x != nil {
		return x.ApprovalRequest
	}
	return nil
}

func (x *ApprovalQueueUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ApproveRequestRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId           *string                `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3,oneof" json:"question_id,omitempty"`
	QuestionCollectionId *string                `protobuf:"bytes,3,opt,name=question_collection_id,json=questionCollectionId,proto3,oneof" json:"question_collection_id,omitempty"`
	SongId               *string                `protobuf:"bytes,4,opt,name=song_id,json=songId,proto3,oneof" json:"song_id,omitempty"`
	SongCollectionId     *string                `protobuf:"bytes,5,opt,name=song_collection_id,json=songCollectionId,proto3,oneof" json:"song_collection_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApproveRequestRequest) Reset() {
	*x = ApproveRequestRequest{}
	mi := &file_approvalqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestRequest) ProtoMessage() {}

func (x *ApproveRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequestRequest) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApproveRequestRequest) GetQuestionId() string {
	if x != nil && x.QuestionId != nil {
		return *x.QuestionId
	}
	return ""
}

func (x *ApproveRequestRequest) GetQuestionCollectionId() string {
	if x != nil && x.QuestionCollectionId != nil {
		return *x.QuestionCollectionId
	}
	return ""
}

func (x *ApproveRequestRequest) GetSongId() string {
	if x != nil && x.SongId != nil {
		return *x.SongId
	}
	return ""
}

func (x *ApproveRequestRequest) GetSongCollectionId() string {
	if x != nil && x.SongCollectionId != nil {
		return *x.SongCollectionId
	}
	return ""
}

type ApproveRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequestResponse) Reset() {
	*x = ApproveRequestResponse{}
	mi := &file_approvalqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestResponse) ProtoMessage() {}

func (x *ApproveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestResponse.ProtoReflect.Descriptor instead.
func (*ApproveRequestResponse) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAllApprovalRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllApprovalRequestsRequest) Reset() {
	*x = GetAllApprovalRequestsRequest{}
	mi := &file_approvalqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllApprovalRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllApprovalRequestsRequest) ProtoMessage() {}

func (x *GetAllApprovalRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllApprovalRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetAllApprovalRequestsRequest) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllApprovalRequestsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllApprovalRequestsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ApprovalRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId           *string                `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3,oneof" json:"question_id,omitempty"`
	QuestionCollectionId *string                `protobuf:"bytes,3,opt,name=question_collection_id,json=questionCollectionId,proto3,oneof" json:"question_collection_id,omitempty"`
	SongId               *string                `protobuf:"bytes,4,opt,name=song_id,json=songId,proto3,oneof" json:"song_id,omitempty"`
	SongCollectionId     *string                `protobuf:"bytes,5,opt,name=song_collection_id,json=songCollectionId,proto3,oneof" json:"song_collection_id,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_approvalqueue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApprovalRequest) GetQuestionId() string {
	if x != nil && x.QuestionId != nil {
		return *x.QuestionId
	}
	return ""
}

func (x *ApprovalRequest) GetQuestionCollectionId() string {
	if x != nil && x.QuestionCollectionId != nil {
		return *x.QuestionCollectionId
	}
	return ""
}

func (x *ApprovalRequest) GetSongId() string {
	if x != nil && x.SongId != nil {
		return *x.SongId
	}
	return ""
}

func (x *ApprovalRequest) GetSongCollectionId() string {
	if x != nil && x.SongCollectionId != nil {
		return *x.SongCollectionId
	}
	return ""
}

func (x *ApprovalRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAllApprovalRequestsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApprovalRequests []*ApprovalRequest     `protobuf:"bytes,1,rep,name=approval_requests,json=approvalRequests,proto3" json:"approval_requests,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllApprovalRequestsResponse) Reset() {
	*x = GetAllApprovalRequestsResponse{}
	mi := &file_approvalqueue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllApprovalRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllApprovalRequestsResponse) ProtoMessage() {}

func (x *GetAllApprovalRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllApprovalRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetAllApprovalRequestsResponse) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllApprovalRequestsResponse) GetApprovalRequests() []*ApprovalRequest {
	if x != nil {
		return x.ApprovalRequests
	}
	return nil
}

type AddToQueueRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId           *string                `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3,oneof" json:"question_id,omitempty"`
	QuestionCollectionId *string                `protobuf:"bytes,3,opt,name=question_collection_id,json=questionCollectionId,proto3,oneof" json:"question_collection_id,omitempty"`
	SongId               *string                `protobuf:"bytes,4,opt,name=song_id,json=songId,proto3,oneof" json:"song_id,omitempty"`
	SongCollectionId     *string                `protobuf:"bytes,5,opt,name=song_collection_id,json=songCollectionId,proto3,oneof" json:"song_collection_id,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddToQueueRequest) Reset() {
	*x = AddToQueueRequest{}
	mi := &file_approvalqueue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToQueueRequest) ProtoMessage() {}

func (x *AddToQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToQueueRequest.ProtoReflect.Descriptor instead.
func (*AddToQueueRequest) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{7}
}

func (x *AddToQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToQueueRequest) GetQuestionId() string {
	if x != nil && x.QuestionId != nil {
		return *x.QuestionId
	}
	return ""
}

func (x *AddToQueueRequest) GetQuestionCollectionId() string {
	if x != nil && x.QuestionCollectionId != nil {
		return *x.QuestionCollectionId
	}
	return ""
}

func (x *AddToQueueRequest) GetSongId() string {
	if x != nil && x.SongId != nil {
		return *x.SongId
	}
	return ""
}

func (x *AddToQueueRequest) GetSongCollectionId() string {
	if x != nil && x.SongCollectionId != nil {
		return *x.SongCollectionId
	}
	return ""
}

func (x *AddToQueueRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AddToQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToQueueResponse) Reset() {
	*x = AddToQueueResponse{}
	mi := &file_approvalqueue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToQueueResponse) ProtoMessage() {}

func (x *AddToQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToQueueResponse.ProtoReflect.Descriptor instead.
func (*AddToQueueResponse) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{8}
}

func (x *AddToQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveFromQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromQueueRequest) Reset() {
	*x = RemoveFromQueueRequest{}
	mi := &file_approvalqueue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromQueueRequest) ProtoMessage() {}

func (x *RemoveFromQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromQueueRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromQueueRequest) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFromQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFromQueueRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type RemoveFromQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromQueueResponse) Reset() {
	*x = RemoveFromQueueResponse{}
	mi := &file_approvalqueue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromQueueResponse) ProtoMessage() {}

func (x *RemoveFromQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approvalqueue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromQueueResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromQueueResponse) Descriptor() ([]byte, []int) {
	return file_approvalqueue_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveFromQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_approvalqueue_proto protoreflect.FileDescriptor

const file_approvalqueue_proto_rawDesc = "" +
	"\n" +
	"\x13approvalqueue.proto\x12\x06protos\"\x1c\n" +
	"\x1aStreamApprovalQueueRequest\"\x8f\x01\n" +
	"\x13ApprovalQueueUpdate\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12B\n" +
	"\x10approval_request\x18\x02 \x01(\v2\x17.protos.ApprovalRequestR\x0fapprovalRequest\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xb0\x02\n" +
	"\x15ApproveRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\vquestion_id\x18\x02 \x01(\tH\x00R\n" +
	"questionId\x88\x01\x01\x129\n" +
	"\x16question_collection_id\x18\x03 \x01(\tH\x01R\x14questionCollectionId\x88\x01\x01\x12\x1c\n" +
	"\asong_id\x18\x04 \x01(\tH\x02R\x06songId\x88\x01\x01\x121\n" +
	"\x12song_collection_id\x18\x05 \x01(\tH\x03R\x10songCollectionId\x88\x01\x01B\x0e\n" +
	"\f_question_idB\x19\n" +
	"\x17_question_collection_idB\n" +
	"\n" +
	"\b_song_idB\x15\n" +
	"\x13_song_collection_id\"2\n" +
	"\x16ApproveRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x1dGetAllApprovalRequestsRequest\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xc9\x02\n" +
	"\x0fApprovalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\vquestion_id\x18\x02 \x01(\tH\x00R\n" +
	"questionId\x88\x01\x01\x129\n" +
	"\x16question_collection_id\x18\x03 \x01(\tH\x01R\x14questionCollectionId\x88\x01\x01\x12\x1c\n" +
	"\asong_id\x18\x04 \x01(\tH\x02R\x06songId\x88\x01\x01\x121\n" +
	"\x12song_collection_id\x18\x05 \x01(\tH\x03R\x10songCollectionId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\x0e\n" +
	"\f_question_idB\x19\n" +
	"\x17_question_collection_idB\n" +
	"\n" +
	"\b_song_idB\x15\n" +
	"\x13_song_collection_id\"f\n" +
	"\x1eGetAllApprovalRequestsResponse\x12D\n" +
	"\x11approval_requests\x18\x01 \x03(\v2\x17.protos.ApprovalRequestR\x10approvalRequests\"\xcb\x02\n" +
	"\x11AddToQueueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\vquestion_id\x18\x02 \x01(\tH\x00R\n" +
	"questionId\x88\x01\x01\x129\n" +
	"\x16question_collection_id\x18\x03 \x01(\tH\x01R\x14questionCollectionId\x88\x01\x01\x12\x1c\n" +
	"\asong_id\x18\x04 \x01(\tH\x02R\x06songId\x88\x01\x01\x121\n" +
	"\x12song_collection_id\x18\x05 \x01(\tH\x03R\x10songCollectionId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\x0e\n" +
	"\f_question_idB\x19\n" +
	"\x17_question_collection_idB\n" +
	"\n" +
	"\b_song_idB\x15\n" +
	"\x13_song_collection_id\".\n" +
	"\x12AddToQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x16RemoveFromQueueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\"3\n" +
	"\x17RemoveFromQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcd\x03\n" +
	"\x14ApprovalQueueService\x12E\n" +
	"\n" +
	"AddToQueue\x12\x19.protos.AddToQueueRequest\x1a\x1a.protos.AddToQueueResponse\"\x00\x12T\n" +
	"\x0fRemoveFromQueue\x12\x1e.protos.RemoveFromQueueRequest\x1a\x1f.protos.RemoveFromQueueResponse\"\x00\x12i\n" +
	"\x16GetAllApprovalRequests\x12%.protos.GetAllApprovalRequestsRequest\x1a&.protos.GetAllApprovalRequestsResponse\"\x00\x12Q\n" +
	"\x0eApproveRequest\x12\x1d.protos.ApproveRequestRequest\x1a\x1e.protos.ApproveRequestResponse\"\x00\x12Z\n" +
	"\x13StreamApprovalQueue\x12\".protos.StreamApprovalQueueRequest\x1a\x1b.protos.ApprovalQueueUpdate\"\x000\x01B\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_approvalqueue_proto_rawDescOnce sync.Once
	file_approvalqueue_proto_rawDescData []byte
)

func file_approvalqueue_proto_rawDescGZIP() []byte {
	file_approvalqueue_proto_rawDescOnce.Do(func() {
		file_approvalqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_approvalqueue_proto_rawDesc), len(file_approvalqueue_proto_rawDesc)))
	})
	return file_approvalqueue_proto_rawDescData
}

var file_approvalqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_approvalqueue_proto_goTypes = []any{
	(*StreamApprovalQueueRequest)(nil),     // 0: protos.StreamApprovalQueueRequest
	(*ApprovalQueueUpdate)(nil),            // 1: protos.ApprovalQueueUpdate
	(*ApproveRequestRequest)(nil),          // 2: protos.ApproveRequestRequest
	(*ApproveRequestResponse)(nil),         // 3: protos.ApproveRequestResponse
	(*GetAllApprovalRequestsRequest)(nil),  // 4: protos.GetAllApprovalRequestsRequest
	(*ApprovalRequest)(nil),                // 5: protos.ApprovalRequest
	(*GetAllApprovalRequestsResponse)(nil), // 6: protos.GetAllApprovalRequestsResponse
	(*AddToQueueRequest)(nil),              // 7: protos.AddToQueueRequest
	(*AddToQueueResponse)(nil),             // 8: protos.AddToQueueResponse
	(*RemoveFromQueueRequest)(nil),         // 9: protos.RemoveFromQueueRequest
	(*RemoveFromQueueResponse)(nil),        // 10: protos.RemoveFromQueueResponse
}
var file_approvalqueue_proto_depIdxs = []int32{
	5,  // 0: protos.ApprovalQueueUpdate.approval_request:type_name -> protos.ApprovalRequest
	5,  // 1: protos.GetAllApprovalRequestsResponse.approval_requests:type_name -> protos.ApprovalRequest
	7,  // 2: protos.ApprovalQueueService.AddToQueue:input_type -> protos.AddToQueueRequest
	9,  // 3: protos.ApprovalQueueService.RemoveFromQueue:input_type -> protos.RemoveFromQueueRequest
	4,  // 4: protos.ApprovalQueueService.GetAllApprovalRequests:input_type -> protos.GetAllApprovalRequestsRequest
	2,  // 5: protos.ApprovalQueueService.ApproveRequest:input_type -> protos.ApproveRequestRequest
	0,  // 6: protos.ApprovalQueueService.StreamApprovalQueue:input_type -> protos.StreamApprovalQueueRequest
	8,  // 7: protos.ApprovalQueueService.AddToQueue:output_type -> protos.AddToQueueResponse
	10, // 8: protos.ApprovalQueueService.RemoveFromQueue:output_type -> protos.RemoveFromQueueResponse
	6,  // 9: protos.ApprovalQueueService.GetAllApprovalRequests:output_type -> protos.GetAllApprovalRequestsResponse
	3,  // 10: protos.ApprovalQueueService.ApproveRequest:output_type -> protos.ApproveRequestResponse
	1,  // 11: protos.ApprovalQueueService.StreamApprovalQueue:output_type -> protos.ApprovalQueueUpdate
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_approvalqueue_proto_init() }
func file_approvalqueue_proto_init() {
	if File_approvalqueue_proto != nil {
		return
	}
	file_approvalqueue_proto_msgTypes[2].OneofWrappers = []any{}
	file_approvalqueue_proto_msgTypes[5].OneofWrappers = []any{}
	file_approvalqueue_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_approvalqueue_proto_rawDesc), len(file_approvalqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_approvalqueue_proto_goTypes,
		DependencyIndexes: file_approvalqueue_proto_depIdxs,
		MessageInfos:      file_approvalqueue_proto_msgTypes,
	}.Build()
	File_approvalqueue_proto = out.File
	file_approvalqueue_proto_goTypes = nil
	file_approvalqueue_proto_depIdxs = nil
}
