// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gamemodes.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndividualGameModes int32

const (
	IndividualGameModes_INDIVIDUAL_GAME_MODES_UNSPECIFIED                   IndividualGameModes = 0
	IndividualGameModes_INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_TRIVIA          IndividualGameModes = 1
	IndividualGameModes_INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_GUESS_THAT_SONG IndividualGameModes = 2
	IndividualGameModes_INDIVIDUAL_GAME_MODES_MULTIPLAYER_GUESS_THAT_SONG   IndividualGameModes = 3
	IndividualGameModes_INDIVIDUAL_GAME_MODES_MULTIPLAYER_TRIVIA            IndividualGameModes = 4
)

// Enum value maps for IndividualGameModes.
var (
	IndividualGameModes_name = map[int32]string{
		0: "INDIVIDUAL_GAME_MODES_UNSPECIFIED",
		1: "INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_TRIVIA",
		2: "INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_GUESS_THAT_SONG",
		3: "INDIVIDUAL_GAME_MODES_MULTIPLAYER_GUESS_THAT_SONG",
		4: "INDIVIDUAL_GAME_MODES_MULTIPLAYER_TRIVIA",
	}
	IndividualGameModes_value = map[string]int32{
		"INDIVIDUAL_GAME_MODES_UNSPECIFIED":                   0,
		"INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_TRIVIA":          1,
		"INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_GUESS_THAT_SONG": 2,
		"INDIVIDUAL_GAME_MODES_MULTIPLAYER_GUESS_THAT_SONG":   3,
		"INDIVIDUAL_GAME_MODES_MULTIPLAYER_TRIVIA":            4,
	}
)

func (x IndividualGameModes) Enum() *IndividualGameModes {
	p := new(IndividualGameModes)
	*p = x
	return p
}

func (x IndividualGameModes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndividualGameModes) Descriptor() protoreflect.EnumDescriptor {
	return file_gamemodes_proto_enumTypes[0].Descriptor()
}

func (IndividualGameModes) Type() protoreflect.EnumType {
	return &file_gamemodes_proto_enumTypes[0]
}

func (x IndividualGameModes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndividualGameModes.Descriptor instead.
func (IndividualGameModes) EnumDescriptor() ([]byte, []int) {
	return file_gamemodes_proto_rawDescGZIP(), []int{0}
}

type TriviaCategories int32

const (
	TriviaCategories_TRIVIA_CATEGORIES_TRIVIA_CATEGORY_UNSPECIFIED TriviaCategories = 0
	TriviaCategories_TRIVIA_CATEGORIES_SONIC_ADVENTURES_1_TRIVIA   TriviaCategories = 2
	TriviaCategories_TRIVIA_CATEGORIES_SONIC_ADVENTURES_2_TRIVIA   TriviaCategories = 1
	TriviaCategories_TRIVIA_CATEGORIES_SONIC_HEROES_TRIVIA         TriviaCategories = 3
)

// Enum value maps for TriviaCategories.
var (
	TriviaCategories_name = map[int32]string{
		0: "TRIVIA_CATEGORIES_TRIVIA_CATEGORY_UNSPECIFIED",
		2: "TRIVIA_CATEGORIES_SONIC_ADVENTURES_1_TRIVIA",
		1: "TRIVIA_CATEGORIES_SONIC_ADVENTURES_2_TRIVIA",
		3: "TRIVIA_CATEGORIES_SONIC_HEROES_TRIVIA",
	}
	TriviaCategories_value = map[string]int32{
		"TRIVIA_CATEGORIES_TRIVIA_CATEGORY_UNSPECIFIED": 0,
		"TRIVIA_CATEGORIES_SONIC_ADVENTURES_1_TRIVIA":   2,
		"TRIVIA_CATEGORIES_SONIC_ADVENTURES_2_TRIVIA":   1,
		"TRIVIA_CATEGORIES_SONIC_HEROES_TRIVIA":         3,
	}
)

func (x TriviaCategories) Enum() *TriviaCategories {
	p := new(TriviaCategories)
	*p = x
	return p
}

func (x TriviaCategories) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriviaCategories) Descriptor() protoreflect.EnumDescriptor {
	return file_gamemodes_proto_enumTypes[1].Descriptor()
}

func (TriviaCategories) Type() protoreflect.EnumType {
	return &file_gamemodes_proto_enumTypes[1]
}

func (x TriviaCategories) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriviaCategories.Descriptor instead.
func (TriviaCategories) EnumDescriptor() ([]byte, []int) {
	return file_gamemodes_proto_rawDescGZIP(), []int{1}
}

type GuessThatSongCategories int32

const (
	GuessThatSongCategories_GUESS_THAT_SONG_CATEGORIES_GUESS_THAT_SONG_CATEGORY_UNSPECIFIED GuessThatSongCategories = 0
	GuessThatSongCategories_GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_1_GUESS_THAT_SONG   GuessThatSongCategories = 2
	GuessThatSongCategories_GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_2_GUESS_THAT_SONG   GuessThatSongCategories = 1
	GuessThatSongCategories_GUESS_THAT_SONG_CATEGORIES_SONIC_HEROES_GUESS_THAT_SONG         GuessThatSongCategories = 3
)

// Enum value maps for GuessThatSongCategories.
var (
	GuessThatSongCategories_name = map[int32]string{
		0: "GUESS_THAT_SONG_CATEGORIES_GUESS_THAT_SONG_CATEGORY_UNSPECIFIED",
		2: "GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_1_GUESS_THAT_SONG",
		1: "GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_2_GUESS_THAT_SONG",
		3: "GUESS_THAT_SONG_CATEGORIES_SONIC_HEROES_GUESS_THAT_SONG",
	}
	GuessThatSongCategories_value = map[string]int32{
		"GUESS_THAT_SONG_CATEGORIES_GUESS_THAT_SONG_CATEGORY_UNSPECIFIED": 0,
		"GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_1_GUESS_THAT_SONG":   2,
		"GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_2_GUESS_THAT_SONG":   1,
		"GUESS_THAT_SONG_CATEGORIES_SONIC_HEROES_GUESS_THAT_SONG":         3,
	}
)

func (x GuessThatSongCategories) Enum() *GuessThatSongCategories {
	p := new(GuessThatSongCategories)
	*p = x
	return p
}

func (x GuessThatSongCategories) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuessThatSongCategories) Descriptor() protoreflect.EnumDescriptor {
	return file_gamemodes_proto_enumTypes[2].Descriptor()
}

func (GuessThatSongCategories) Type() protoreflect.EnumType {
	return &file_gamemodes_proto_enumTypes[2]
}

func (x GuessThatSongCategories) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuessThatSongCategories.Descriptor instead.
func (GuessThatSongCategories) EnumDescriptor() ([]byte, []int) {
	return file_gamemodes_proto_rawDescGZIP(), []int{2}
}

var File_gamemodes_proto protoreflect.FileDescriptor

const file_gamemodes_proto_rawDesc = "" +
	"\n" +
	"\x0fgamemodes.proto\x12\x06protos*\x8a\x02\n" +
	"\x13IndividualGameModes\x12%\n" +
	"!INDIVIDUAL_GAME_MODES_UNSPECIFIED\x10\x00\x12.\n" +
	"*INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_TRIVIA\x10\x01\x127\n" +
	"3INDIVIDUAL_GAME_MODES_SINGLE_PLAYER_GUESS_THAT_SONG\x10\x02\x125\n" +
	"1INDIVIDUAL_GAME_MODES_MULTIPLAYER_GUESS_THAT_SONG\x10\x03\x12,\n" +
	"(INDIVIDUAL_GAME_MODES_MULTIPLAYER_TRIVIA\x10\x04*\xd2\x01\n" +
	"\x10TriviaCategories\x121\n" +
	"-TRIVIA_CATEGORIES_TRIVIA_CATEGORY_UNSPECIFIED\x10\x00\x12/\n" +
	"+TRIVIA_CATEGORIES_SONIC_ADVENTURES_1_TRIVIA\x10\x02\x12/\n" +
	"+TRIVIA_CATEGORIES_SONIC_ADVENTURES_2_TRIVIA\x10\x01\x12)\n" +
	"%TRIVIA_CATEGORIES_SONIC_HEROES_TRIVIA\x10\x03*\xa1\x02\n" +
	"\x17GuessThatSongCategories\x12C\n" +
	"?GUESS_THAT_SONG_CATEGORIES_GUESS_THAT_SONG_CATEGORY_UNSPECIFIED\x10\x00\x12A\n" +
	"=GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_1_GUESS_THAT_SONG\x10\x02\x12A\n" +
	"=GUESS_THAT_SONG_CATEGORIES_SONIC_ADVENTURES_2_GUESS_THAT_SONG\x10\x01\x12;\n" +
	"7GUESS_THAT_SONG_CATEGORIES_SONIC_HEROES_GUESS_THAT_SONG\x10\x03B\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_gamemodes_proto_rawDescOnce sync.Once
	file_gamemodes_proto_rawDescData []byte
)

func file_gamemodes_proto_rawDescGZIP() []byte {
	file_gamemodes_proto_rawDescOnce.Do(func() {
		file_gamemodes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamemodes_proto_rawDesc), len(file_gamemodes_proto_rawDesc)))
	})
	return file_gamemodes_proto_rawDescData
}

var file_gamemodes_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gamemodes_proto_goTypes = []any{
	(IndividualGameModes)(0),     // 0: protos.IndividualGameModes
	(TriviaCategories)(0),        // 1: protos.TriviaCategories
	(GuessThatSongCategories)(0), // 2: protos.GuessThatSongCategories
}
var file_gamemodes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gamemodes_proto_init() }
func file_gamemodes_proto_init() {
	if File_gamemodes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamemodes_proto_rawDesc), len(file_gamemodes_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamemodes_proto_goTypes,
		DependencyIndexes: file_gamemodes_proto_depIdxs,
		EnumInfos:         file_gamemodes_proto_enumTypes,
	}.Build()
	File_gamemodes_proto = out.File
	file_gamemodes_proto_goTypes = nil
	file_gamemodes_proto_depIdxs = nil
}
