// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: guessthatsong.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SongHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongHint) Reset() {
	*x = SongHint{}
	mi := &file_guessthatsong_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongHint) ProtoMessage() {}

func (x *SongHint) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongHint.ProtoReflect.Descriptor instead.
func (*SongHint) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{0}
}

func (x *SongHint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SongHint) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SongTitle     string                 `protobuf:"bytes,2,opt,name=song_title,json=songTitle,proto3" json:"song_title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	ReleaseYear   string                 `protobuf:"bytes,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty    string                 `protobuf:"bytes,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	PlaysPerRound int32                  `protobuf:"varint,8,opt,name=plays_per_round,json=playsPerRound,proto3" json:"plays_per_round,omitempty"`
	ClipDuration  int32                  `protobuf:"varint,9,opt,name=clip_duration,json=clipDuration,proto3" json:"clip_duration,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,10,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	Hints         []*SongHint            `protobuf:"bytes,11,rep,name=hints,proto3" json:"hints,omitempty"`
	PictureUrl    *string                `protobuf:"bytes,12,opt,name=picture_url,json=pictureUrl,proto3,oneof" json:"picture_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_guessthatsong_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{1}
}

func (x *Song) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Song) GetSongTitle() string {
	if x != nil {
		return x.SongTitle
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Song) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Song) GetReleaseYear() string {
	if x != nil {
		return x.ReleaseYear
	}
	return ""
}

func (x *Song) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Song) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Song) GetPlaysPerRound() int32 {
	if x != nil {
		return x.PlaysPerRound
	}
	return 0
}

func (x *Song) GetClipDuration() int32 {
	if x != nil {
		return x.ClipDuration
	}
	return 0
}

func (x *Song) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *Song) GetHints() []*SongHint {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *Song) GetPictureUrl() string {
	if x != nil && x.PictureUrl != nil {
		return *x.PictureUrl
	}
	return ""
}

type GetRandomSongsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	HowManyRounds int32                  `protobuf:"varint,2,opt,name=how_many_rounds,json=howManyRounds,proto3" json:"how_many_rounds,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomSongsRequest) Reset() {
	*x = GetRandomSongsRequest{}
	mi := &file_guessthatsong_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomSongsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomSongsRequest) ProtoMessage() {}

func (x *GetRandomSongsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomSongsRequest.ProtoReflect.Descriptor instead.
func (*GetRandomSongsRequest) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{2}
}

func (x *GetRandomSongsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetRandomSongsRequest) GetHowManyRounds() int32 {
	if x != nil {
		return x.HowManyRounds
	}
	return 0
}

func (x *GetRandomSongsRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

type GetRandomSongsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomSongsResponse) Reset() {
	*x = GetRandomSongsResponse{}
	mi := &file_guessthatsong_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomSongsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomSongsResponse) ProtoMessage() {}

func (x *GetRandomSongsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomSongsResponse.ProtoReflect.Descriptor instead.
func (*GetRandomSongsResponse) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{3}
}

func (x *GetRandomSongsResponse) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

type CreateSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSongRequest) Reset() {
	*x = CreateSongRequest{}
	mi := &file_guessthatsong_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongRequest) ProtoMessage() {}

func (x *CreateSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongRequest.ProtoReflect.Descriptor instead.
func (*CreateSongRequest) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSongRequest) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type CreateSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSongResponse) Reset() {
	*x = CreateSongResponse{}
	mi := &file_guessthatsong_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongResponse) ProtoMessage() {}

func (x *CreateSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongResponse.ProtoReflect.Descriptor instead.
func (*CreateSongResponse) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSongResponse) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type GetSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongRequest) Reset() {
	*x = GetSongRequest{}
	mi := &file_guessthatsong_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongRequest) ProtoMessage() {}

func (x *GetSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongRequest.ProtoReflect.Descriptor instead.
func (*GetSongRequest) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{6}
}

func (x *GetSongRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongResponse) Reset() {
	*x = GetSongResponse{}
	mi := &file_guessthatsong_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongResponse) ProtoMessage() {}

func (x *GetSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongResponse.ProtoReflect.Descriptor instead.
func (*GetSongResponse) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{7}
}

func (x *GetSongResponse) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type GetRandomSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomSongRequest) Reset() {
	*x = GetRandomSongRequest{}
	mi := &file_guessthatsong_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomSongRequest) ProtoMessage() {}

func (x *GetRandomSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomSongRequest.ProtoReflect.Descriptor instead.
func (*GetRandomSongRequest) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{8}
}

func (x *GetRandomSongRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetRandomSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomSongResponse) Reset() {
	*x = GetRandomSongResponse{}
	mi := &file_guessthatsong_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomSongResponse) ProtoMessage() {}

func (x *GetRandomSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomSongResponse.ProtoReflect.Descriptor instead.
func (*GetRandomSongResponse) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{9}
}

func (x *GetRandomSongResponse) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type UpdateSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSongRequest) Reset() {
	*x = UpdateSongRequest{}
	mi := &file_guessthatsong_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSongRequest) ProtoMessage() {}

func (x *UpdateSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSongRequest.ProtoReflect.Descriptor instead.
func (*UpdateSongRequest) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSongRequest) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type UpdateSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSongResponse) Reset() {
	*x = UpdateSongResponse{}
	mi := &file_guessthatsong_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSongResponse) ProtoMessage() {}

func (x *UpdateSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSongResponse.ProtoReflect.Descriptor instead.
func (*UpdateSongResponse) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSongResponse) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type DeleteSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSongRequest) Reset() {
	*x = DeleteSongRequest{}
	mi := &file_guessthatsong_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSongRequest) ProtoMessage() {}

func (x *DeleteSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSongRequest.ProtoReflect.Descriptor instead.
func (*DeleteSongRequest) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSongRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSongResponse) Reset() {
	*x = DeleteSongResponse{}
	mi := &file_guessthatsong_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSongResponse) ProtoMessage() {}

func (x *DeleteSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSongResponse.ProtoReflect.Descriptor instead.
func (*DeleteSongResponse) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSongResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSongRequest) Reset() {
	*x = SearchSongRequest{}
	mi := &file_guessthatsong_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSongRequest) ProtoMessage() {}

func (x *SearchSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSongRequest.ProtoReflect.Descriptor instead.
func (*SearchSongRequest) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{14}
}

func (x *SearchSongRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSongResponse) Reset() {
	*x = SearchSongResponse{}
	mi := &file_guessthatsong_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSongResponse) ProtoMessage() {}

func (x *SearchSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessthatsong_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSongResponse.ProtoReflect.Descriptor instead.
func (*SearchSongResponse) Descriptor() ([]byte, []int) {
	return file_guessthatsong_proto_rawDescGZIP(), []int{15}
}

func (x *SearchSongResponse) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

var File_guessthatsong_proto protoreflect.FileDescriptor

const file_guessthatsong_proto_rawDesc = "" +
	"\n" +
	"\x13guessthatsong.proto\x12\x06protos\".\n" +
	"\bSongHint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x8a\x03\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"song_title\x18\x02 \x01(\tR\tsongTitle\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12!\n" +
	"\frelease_year\x18\x05 \x01(\tR\vreleaseYear\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\tR\n" +
	"difficulty\x12&\n" +
	"\x0fplays_per_round\x18\b \x01(\x05R\rplaysPerRound\x12#\n" +
	"\rclip_duration\x18\t \x01(\x05R\fclipDuration\x12\x1b\n" +
	"\taudio_url\x18\n" +
	" \x01(\tR\baudioUrl\x12&\n" +
	"\x05hints\x18\v \x03(\v2\x10.protos.SongHintR\x05hints\x12$\n" +
	"\vpicture_url\x18\f \x01(\tH\x00R\n" +
	"pictureUrl\x88\x01\x01B\x0e\n" +
	"\f_picture_url\"{\n" +
	"\x15GetRandomSongsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12&\n" +
	"\x0fhow_many_rounds\x18\x02 \x01(\x05R\rhowManyRounds\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\"<\n" +
	"\x16GetRandomSongsResponse\x12\"\n" +
	"\x05songs\x18\x01 \x03(\v2\f.protos.SongR\x05songs\"5\n" +
	"\x11CreateSongRequest\x12 \n" +
	"\x04song\x18\x01 \x01(\v2\f.protos.SongR\x04song\"6\n" +
	"\x12CreateSongResponse\x12 \n" +
	"\x04song\x18\x01 \x01(\v2\f.protos.SongR\x04song\" \n" +
	"\x0eGetSongRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x0fGetSongResponse\x12 \n" +
	"\x04song\x18\x01 \x01(\v2\f.protos.SongR\x04song\"2\n" +
	"\x14GetRandomSongRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"9\n" +
	"\x15GetRandomSongResponse\x12 \n" +
	"\x04song\x18\x01 \x01(\v2\f.protos.SongR\x04song\"5\n" +
	"\x11UpdateSongRequest\x12 \n" +
	"\x04song\x18\x01 \x01(\v2\f.protos.SongR\x04song\"6\n" +
	"\x12UpdateSongResponse\x12 \n" +
	"\x04song\x18\x01 \x01(\v2\f.protos.SongR\x04song\"#\n" +
	"\x11DeleteSongRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteSongResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x11SearchSongRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"8\n" +
	"\x12SearchSongResponse\x12\"\n" +
	"\x05songs\x18\x01 \x03(\v2\f.protos.SongR\x05songs2\x93\x04\n" +
	"\x14GuessThatSongService\x12E\n" +
	"\n" +
	"CreateSong\x12\x19.protos.CreateSongRequest\x1a\x1a.protos.CreateSongResponse\"\x00\x12<\n" +
	"\aGetSong\x12\x16.protos.GetSongRequest\x1a\x17.protos.GetSongResponse\"\x00\x12N\n" +
	"\rGetRandomSong\x12\x1c.protos.GetRandomSongRequest\x1a\x1d.protos.GetRandomSongResponse\"\x00\x12Q\n" +
	"\x0eGetRandomSongs\x12\x1d.protos.GetRandomSongsRequest\x1a\x1e.protos.GetRandomSongsResponse\"\x00\x12E\n" +
	"\n" +
	"UpdateSong\x12\x19.protos.UpdateSongRequest\x1a\x1a.protos.UpdateSongResponse\"\x00\x12E\n" +
	"\n" +
	"DeleteSong\x12\x19.protos.DeleteSongRequest\x1a\x1a.protos.DeleteSongResponse\"\x00\x12E\n" +
	"\n" +
	"SearchSong\x12\x19.protos.SearchSongRequest\x1a\x1a.protos.SearchSongResponse\"\x00B\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_guessthatsong_proto_rawDescOnce sync.Once
	file_guessthatsong_proto_rawDescData []byte
)

func file_guessthatsong_proto_rawDescGZIP() []byte {
	file_guessthatsong_proto_rawDescOnce.Do(func() {
		file_guessthatsong_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guessthatsong_proto_rawDesc), len(file_guessthatsong_proto_rawDesc)))
	})
	return file_guessthatsong_proto_rawDescData
}

var file_guessthatsong_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_guessthatsong_proto_goTypes = []any{
	(*SongHint)(nil),               // 0: protos.SongHint
	(*Song)(nil),                   // 1: protos.Song
	(*GetRandomSongsRequest)(nil),  // 2: protos.GetRandomSongsRequest
	(*GetRandomSongsResponse)(nil), // 3: protos.GetRandomSongsResponse
	(*CreateSongRequest)(nil),      // 4: protos.CreateSongRequest
	(*CreateSongResponse)(nil),     // 5: protos.CreateSongResponse
	(*GetSongRequest)(nil),         // 6: protos.GetSongRequest
	(*GetSongResponse)(nil),        // 7: protos.GetSongResponse
	(*GetRandomSongRequest)(nil),   // 8: protos.GetRandomSongRequest
	(*GetRandomSongResponse)(nil),  // 9: protos.GetRandomSongResponse
	(*UpdateSongRequest)(nil),      // 10: protos.UpdateSongRequest
	(*UpdateSongResponse)(nil),     // 11: protos.UpdateSongResponse
	(*DeleteSongRequest)(nil),      // 12: protos.DeleteSongRequest
	(*DeleteSongResponse)(nil),     // 13: protos.DeleteSongResponse
	(*SearchSongRequest)(nil),      // 14: protos.SearchSongRequest
	(*SearchSongResponse)(nil),     // 15: protos.SearchSongResponse
}
var file_guessthatsong_proto_depIdxs = []int32{
	0,  // 0: protos.Song.hints:type_name -> protos.SongHint
	1,  // 1: protos.GetRandomSongsResponse.songs:type_name -> protos.Song
	1,  // 2: protos.CreateSongRequest.song:type_name -> protos.Song
	1,  // 3: protos.CreateSongResponse.song:type_name -> protos.Song
	1,  // 4: protos.GetSongResponse.song:type_name -> protos.Song
	1,  // 5: protos.GetRandomSongResponse.song:type_name -> protos.Song
	1,  // 6: protos.UpdateSongRequest.song:type_name -> protos.Song
	1,  // 7: protos.UpdateSongResponse.song:type_name -> protos.Song
	1,  // 8: protos.SearchSongResponse.songs:type_name -> protos.Song
	4,  // 9: protos.GuessThatSongService.CreateSong:input_type -> protos.CreateSongRequest
	6,  // 10: protos.GuessThatSongService.GetSong:input_type -> protos.GetSongRequest
	8,  // 11: protos.GuessThatSongService.GetRandomSong:input_type -> protos.GetRandomSongRequest
	2,  // 12: protos.GuessThatSongService.GetRandomSongs:input_type -> protos.GetRandomSongsRequest
	10, // 13: protos.GuessThatSongService.UpdateSong:input_type -> protos.UpdateSongRequest
	12, // 14: protos.GuessThatSongService.DeleteSong:input_type -> protos.DeleteSongRequest
	14, // 15: protos.GuessThatSongService.SearchSong:input_type -> protos.SearchSongRequest
	5,  // 16: protos.GuessThatSongService.CreateSong:output_type -> protos.CreateSongResponse
	7,  // 17: protos.GuessThatSongService.GetSong:output_type -> protos.GetSongResponse
	9,  // 18: protos.GuessThatSongService.GetRandomSong:output_type -> protos.GetRandomSongResponse
	3,  // 19: protos.GuessThatSongService.GetRandomSongs:output_type -> protos.GetRandomSongsResponse
	11, // 20: protos.GuessThatSongService.UpdateSong:output_type -> protos.UpdateSongResponse
	13, // 21: protos.GuessThatSongService.DeleteSong:output_type -> protos.DeleteSongResponse
	15, // 22: protos.GuessThatSongService.SearchSong:output_type -> protos.SearchSongResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_guessthatsong_proto_init() }
func file_guessthatsong_proto_init() {
	if File_guessthatsong_proto != nil {
		return
	}
	file_guessthatsong_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guessthatsong_proto_rawDesc), len(file_guessthatsong_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guessthatsong_proto_goTypes,
		DependencyIndexes: file_guessthatsong_proto_depIdxs,
		MessageInfos:      file_guessthatsong_proto_msgTypes,
	}.Build()
	File_guessthatsong_proto = out.File
	file_guessthatsong_proto_goTypes = nil
	file_guessthatsong_proto_depIdxs = nil
}
