// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: leaderboard.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderboardPlayer struct {
	state                          protoimpl.MessageState      `protogen:"open.v1"`
	Name                           string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score                          int32                       `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	PlaceInLeaderBoardForEachRound []*LeaderboardHistoryPlayer `protobuf:"bytes,3,rep,name=place_in_leader_board_for_each_round,json=placeInLeaderBoardForEachRound,proto3" json:"place_in_leader_board_for_each_round,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *LeaderboardPlayer) Reset() {
	*x = LeaderboardPlayer{}
	mi := &file_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardPlayer) ProtoMessage() {}

func (x *LeaderboardPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardPlayer.ProtoReflect.Descriptor instead.
func (*LeaderboardPlayer) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderboardPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderboardPlayer) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardPlayer) GetPlaceInLeaderBoardForEachRound() []*LeaderboardHistoryPlayer {
	if x != nil {
		return x.PlaceInLeaderBoardForEachRound
	}
	return nil
}

type LeaderboardHistoryPlayer struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	PlaceInLeaderBoardForEachRound string                 `protobuf:"bytes,1,opt,name=place_in_leader_board_for_each_round,json=placeInLeaderBoardForEachRound,proto3" json:"place_in_leader_board_for_each_round,omitempty"`
	Event                          string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *LeaderboardHistoryPlayer) Reset() {
	*x = LeaderboardHistoryPlayer{}
	mi := &file_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardHistoryPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardHistoryPlayer) ProtoMessage() {}

func (x *LeaderboardHistoryPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardHistoryPlayer.ProtoReflect.Descriptor instead.
func (*LeaderboardHistoryPlayer) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderboardHistoryPlayer) GetPlaceInLeaderBoardForEachRound() string {
	if x != nil {
		return x.PlaceInLeaderBoardForEachRound
	}
	return ""
}

func (x *LeaderboardHistoryPlayer) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type RoomLeaderboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Players       []*LeaderboardPlayer   `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaderboard) Reset() {
	*x = RoomLeaderboard{}
	mi := &file_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaderboard) ProtoMessage() {}

func (x *RoomLeaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaderboard.ProtoReflect.Descriptor instead.
func (*RoomLeaderboard) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *RoomLeaderboard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomLeaderboard) GetPlayers() []*LeaderboardPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type UpdateRoomLeaderboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*UpdateRoomLeaderboardRequest_Email
	//	*UpdateRoomLeaderboardRequest_Username
	Value              isUpdateRoomLeaderboardRequest_Value `protobuf_oneof:"value"`
	Score              int64                                `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	PlaceInLeaderBoard string                               `protobuf:"bytes,4,opt,name=place_in_leader_board,json=placeInLeaderBoard,proto3" json:"place_in_leader_board,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateRoomLeaderboardRequest) Reset() {
	*x = UpdateRoomLeaderboardRequest{}
	mi := &file_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomLeaderboardRequest) ProtoMessage() {}

func (x *UpdateRoomLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoomLeaderboardRequest) GetValue() isUpdateRoomLeaderboardRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateRoomLeaderboardRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Value.(*UpdateRoomLeaderboardRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UpdateRoomLeaderboardRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Value.(*UpdateRoomLeaderboardRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *UpdateRoomLeaderboardRequest) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpdateRoomLeaderboardRequest) GetPlaceInLeaderBoard() string {
	if x != nil {
		return x.PlaceInLeaderBoard
	}
	return ""
}

type isUpdateRoomLeaderboardRequest_Value interface {
	isUpdateRoomLeaderboardRequest_Value()
}

type UpdateRoomLeaderboardRequest_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type UpdateRoomLeaderboardRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*UpdateRoomLeaderboardRequest_Email) isUpdateRoomLeaderboardRequest_Value() {}

func (*UpdateRoomLeaderboardRequest_Username) isUpdateRoomLeaderboardRequest_Value() {}

type UpdateRoomLeaderboardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*UpdateRoomLeaderboardResponse_Email
	//	*UpdateRoomLeaderboardResponse_Username
	Value              isUpdateRoomLeaderboardResponse_Value `protobuf_oneof:"value"`
	Score              int64                                 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	PlaceInLeaderBoard string                                `protobuf:"bytes,4,opt,name=place_in_leader_board,json=placeInLeaderBoard,proto3" json:"place_in_leader_board,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateRoomLeaderboardResponse) Reset() {
	*x = UpdateRoomLeaderboardResponse{}
	mi := &file_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomLeaderboardResponse) ProtoMessage() {}

func (x *UpdateRoomLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoomLeaderboardResponse) GetValue() isUpdateRoomLeaderboardResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateRoomLeaderboardResponse) GetEmail() string {
	if x != nil {
		if x, ok := x.Value.(*UpdateRoomLeaderboardResponse_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UpdateRoomLeaderboardResponse) GetUsername() string {
	if x != nil {
		if x, ok := x.Value.(*UpdateRoomLeaderboardResponse_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *UpdateRoomLeaderboardResponse) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpdateRoomLeaderboardResponse) GetPlaceInLeaderBoard() string {
	if x != nil {
		return x.PlaceInLeaderBoard
	}
	return ""
}

type isUpdateRoomLeaderboardResponse_Value interface {
	isUpdateRoomLeaderboardResponse_Value()
}

type UpdateRoomLeaderboardResponse_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type UpdateRoomLeaderboardResponse_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*UpdateRoomLeaderboardResponse_Email) isUpdateRoomLeaderboardResponse_Value() {}

func (*UpdateRoomLeaderboardResponse_Username) isUpdateRoomLeaderboardResponse_Value() {}

type UpdateGlobalLeaderboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*UpdateGlobalLeaderboardRequest_Email
	//	*UpdateGlobalLeaderboardRequest_Username
	Value              isUpdateGlobalLeaderboardRequest_Value `protobuf_oneof:"value"`
	Score              int64                                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	PlaceInLeaderBoard string                                 `protobuf:"bytes,4,opt,name=place_in_leader_board,json=placeInLeaderBoard,proto3" json:"place_in_leader_board,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateGlobalLeaderboardRequest) Reset() {
	*x = UpdateGlobalLeaderboardRequest{}
	mi := &file_leaderboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalLeaderboardRequest) ProtoMessage() {}

func (x *UpdateGlobalLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*UpdateGlobalLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGlobalLeaderboardRequest) GetValue() isUpdateGlobalLeaderboardRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateGlobalLeaderboardRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Value.(*UpdateGlobalLeaderboardRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UpdateGlobalLeaderboardRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Value.(*UpdateGlobalLeaderboardRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *UpdateGlobalLeaderboardRequest) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpdateGlobalLeaderboardRequest) GetPlaceInLeaderBoard() string {
	if x != nil {
		return x.PlaceInLeaderBoard
	}
	return ""
}

type isUpdateGlobalLeaderboardRequest_Value interface {
	isUpdateGlobalLeaderboardRequest_Value()
}

type UpdateGlobalLeaderboardRequest_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type UpdateGlobalLeaderboardRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*UpdateGlobalLeaderboardRequest_Email) isUpdateGlobalLeaderboardRequest_Value() {}

func (*UpdateGlobalLeaderboardRequest_Username) isUpdateGlobalLeaderboardRequest_Value() {}

type PaginateRoomLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginateRoomLeaderboardRequest) Reset() {
	*x = PaginateRoomLeaderboardRequest{}
	mi := &file_leaderboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginateRoomLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateRoomLeaderboardRequest) ProtoMessage() {}

func (x *PaginateRoomLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateRoomLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*PaginateRoomLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{6}
}

func (x *PaginateRoomLeaderboardRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PaginateRoomLeaderboardRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginateRoomLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PaginateRoomLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboards  []*RoomLeaderboard     `protobuf:"bytes,1,rep,name=leaderboards,proto3" json:"leaderboards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginateRoomLeaderboardResponse) Reset() {
	*x = PaginateRoomLeaderboardResponse{}
	mi := &file_leaderboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginateRoomLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateRoomLeaderboardResponse) ProtoMessage() {}

func (x *PaginateRoomLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateRoomLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*PaginateRoomLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{7}
}

func (x *PaginateRoomLeaderboardResponse) GetLeaderboards() []*RoomLeaderboard {
	if x != nil {
		return x.Leaderboards
	}
	return nil
}

type UpdateGlobalLeaderboardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*UpdateGlobalLeaderboardResponse_TotalPoints
	Value         isUpdateGlobalLeaderboardResponse_Value `protobuf_oneof:"value"`
	Error         string                                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalLeaderboardResponse) Reset() {
	*x = UpdateGlobalLeaderboardResponse{}
	mi := &file_leaderboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalLeaderboardResponse) ProtoMessage() {}

func (x *UpdateGlobalLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*UpdateGlobalLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGlobalLeaderboardResponse) GetValue() isUpdateGlobalLeaderboardResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateGlobalLeaderboardResponse) GetTotalPoints() int64 {
	if x != nil {
		if x, ok := x.Value.(*UpdateGlobalLeaderboardResponse_TotalPoints); ok {
			return x.TotalPoints
		}
	}
	return 0
}

func (x *UpdateGlobalLeaderboardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isUpdateGlobalLeaderboardResponse_Value interface {
	isUpdateGlobalLeaderboardResponse_Value()
}

type UpdateGlobalLeaderboardResponse_TotalPoints struct {
	TotalPoints int64 `protobuf:"varint,1,opt,name=total_points,json=totalPoints,proto3,oneof"`
}

func (*UpdateGlobalLeaderboardResponse_TotalPoints) isUpdateGlobalLeaderboardResponse_Value() {}

type PaginateGlobalLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginateGlobalLeaderboardRequest) Reset() {
	*x = PaginateGlobalLeaderboardRequest{}
	mi := &file_leaderboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginateGlobalLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateGlobalLeaderboardRequest) ProtoMessage() {}

func (x *PaginateGlobalLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateGlobalLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*PaginateGlobalLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{9}
}

func (x *PaginateGlobalLeaderboardRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginateGlobalLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PaginateGlobalLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*LeaderboardPlayer   `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginateGlobalLeaderboardResponse) Reset() {
	*x = PaginateGlobalLeaderboardResponse{}
	mi := &file_leaderboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginateGlobalLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateGlobalLeaderboardResponse) ProtoMessage() {}

func (x *PaginateGlobalLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateGlobalLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*PaginateGlobalLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{10}
}

func (x *PaginateGlobalLeaderboardResponse) GetPlayers() []*LeaderboardPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x11leaderboard.proto\x12\x06protos\"\xad\x01\n" +
	"\x11LeaderboardPlayer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12n\n" +
	"$place_in_leader_board_for_each_round\x18\x03 \x03(\v2 .protos.LeaderboardHistoryPlayerR\x1eplaceInLeaderBoardForEachRound\"~\n" +
	"\x18LeaderboardHistoryPlayer\x12L\n" +
	"$place_in_leader_board_for_each_round\x18\x01 \x01(\tR\x1eplaceInLeaderBoardForEachRound\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\"Z\n" +
	"\x0fRoomLeaderboard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\aplayers\x18\x02 \x03(\v2\x19.protos.LeaderboardPlayerR\aplayers\"\xa6\x01\n" +
	"\x1cUpdateRoomLeaderboardRequest\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x121\n" +
	"\x15place_in_leader_board\x18\x04 \x01(\tR\x12placeInLeaderBoardB\a\n" +
	"\x05value\"\xa7\x01\n" +
	"\x1dUpdateRoomLeaderboardResponse\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x121\n" +
	"\x15place_in_leader_board\x18\x04 \x01(\tR\x12placeInLeaderBoardB\a\n" +
	"\x05value\"\xa8\x01\n" +
	"\x1eUpdateGlobalLeaderboardRequest\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x121\n" +
	"\x15place_in_leader_board\x18\x04 \x01(\tR\x12placeInLeaderBoardB\a\n" +
	"\x05value\"c\n" +
	"\x1ePaginateRoomLeaderboardRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"^\n" +
	"\x1fPaginateRoomLeaderboardResponse\x12;\n" +
	"\fleaderboards\x18\x01 \x03(\v2\x17.protos.RoomLeaderboardR\fleaderboards\"e\n" +
	"\x1fUpdateGlobalLeaderboardResponse\x12#\n" +
	"\ftotal_points\x18\x01 \x01(\x03H\x00R\vtotalPoints\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\a\n" +
	"\x05value\"L\n" +
	" PaginateGlobalLeaderboardRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"X\n" +
	"!PaginateGlobalLeaderboardResponse\x123\n" +
	"\aplayers\x18\x01 \x03(\v2\x19.protos.LeaderboardPlayerR\aplayers2\xcc\x03\n" +
	"\x12LeaderboardService\x12f\n" +
	"\x15UpdateRoomLeaderboard\x12$.protos.UpdateRoomLeaderboardRequest\x1a%.protos.UpdateRoomLeaderboardResponse\"\x00\x12l\n" +
	"\x17PaginateRoomLeaderboard\x12&.protos.PaginateRoomLeaderboardRequest\x1a'.protos.PaginateRoomLeaderboardResponse\"\x00\x12l\n" +
	"\x17UpdateGlobalLeaderboard\x12&.protos.UpdateGlobalLeaderboardRequest\x1a'.protos.UpdateGlobalLeaderboardResponse\"\x00\x12r\n" +
	"\x19PaginateGlobalLeaderboard\x12(.protos.PaginateGlobalLeaderboardRequest\x1a).protos.PaginateGlobalLeaderboardResponse\"\x00B\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_proto_rawDescData
}

var file_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_leaderboard_proto_goTypes = []any{
	(*LeaderboardPlayer)(nil),                 // 0: protos.LeaderboardPlayer
	(*LeaderboardHistoryPlayer)(nil),          // 1: protos.LeaderboardHistoryPlayer
	(*RoomLeaderboard)(nil),                   // 2: protos.RoomLeaderboard
	(*UpdateRoomLeaderboardRequest)(nil),      // 3: protos.UpdateRoomLeaderboardRequest
	(*UpdateRoomLeaderboardResponse)(nil),     // 4: protos.UpdateRoomLeaderboardResponse
	(*UpdateGlobalLeaderboardRequest)(nil),    // 5: protos.UpdateGlobalLeaderboardRequest
	(*PaginateRoomLeaderboardRequest)(nil),    // 6: protos.PaginateRoomLeaderboardRequest
	(*PaginateRoomLeaderboardResponse)(nil),   // 7: protos.PaginateRoomLeaderboardResponse
	(*UpdateGlobalLeaderboardResponse)(nil),   // 8: protos.UpdateGlobalLeaderboardResponse
	(*PaginateGlobalLeaderboardRequest)(nil),  // 9: protos.PaginateGlobalLeaderboardRequest
	(*PaginateGlobalLeaderboardResponse)(nil), // 10: protos.PaginateGlobalLeaderboardResponse
}
var file_leaderboard_proto_depIdxs = []int32{
	1,  // 0: protos.LeaderboardPlayer.place_in_leader_board_for_each_round:type_name -> protos.LeaderboardHistoryPlayer
	0,  // 1: protos.RoomLeaderboard.players:type_name -> protos.LeaderboardPlayer
	2,  // 2: protos.PaginateRoomLeaderboardResponse.leaderboards:type_name -> protos.RoomLeaderboard
	0,  // 3: protos.PaginateGlobalLeaderboardResponse.players:type_name -> protos.LeaderboardPlayer
	3,  // 4: protos.LeaderboardService.UpdateRoomLeaderboard:input_type -> protos.UpdateRoomLeaderboardRequest
	6,  // 5: protos.LeaderboardService.PaginateRoomLeaderboard:input_type -> protos.PaginateRoomLeaderboardRequest
	5,  // 6: protos.LeaderboardService.UpdateGlobalLeaderboard:input_type -> protos.UpdateGlobalLeaderboardRequest
	9,  // 7: protos.LeaderboardService.PaginateGlobalLeaderboard:input_type -> protos.PaginateGlobalLeaderboardRequest
	4,  // 8: protos.LeaderboardService.UpdateRoomLeaderboard:output_type -> protos.UpdateRoomLeaderboardResponse
	7,  // 9: protos.LeaderboardService.PaginateRoomLeaderboard:output_type -> protos.PaginateRoomLeaderboardResponse
	8,  // 10: protos.LeaderboardService.UpdateGlobalLeaderboard:output_type -> protos.UpdateGlobalLeaderboardResponse
	10, // 11: protos.LeaderboardService.PaginateGlobalLeaderboard:output_type -> protos.PaginateGlobalLeaderboardResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_leaderboard_proto_init() }
func file_leaderboard_proto_init() {
	if File_leaderboard_proto != nil {
		return
	}
	file_leaderboard_proto_msgTypes[3].OneofWrappers = []any{
		(*UpdateRoomLeaderboardRequest_Email)(nil),
		(*UpdateRoomLeaderboardRequest_Username)(nil),
	}
	file_leaderboard_proto_msgTypes[4].OneofWrappers = []any{
		(*UpdateRoomLeaderboardResponse_Email)(nil),
		(*UpdateRoomLeaderboardResponse_Username)(nil),
	}
	file_leaderboard_proto_msgTypes[5].OneofWrappers = []any{
		(*UpdateGlobalLeaderboardRequest_Email)(nil),
		(*UpdateGlobalLeaderboardRequest_Username)(nil),
	}
	file_leaderboard_proto_msgTypes[8].OneofWrappers = []any{
		(*UpdateGlobalLeaderboardResponse_TotalPoints)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_proto_depIdxs,
		MessageInfos:      file_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_proto = out.File
	file_leaderboard_proto_goTypes = nil
	file_leaderboard_proto_depIdxs = nil
}
