// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: login.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpUsernameOrEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SignUpUsernameOrEmailRequest_Username
	//	*SignUpUsernameOrEmailRequest_Email
	Value         isSignUpUsernameOrEmailRequest_Value `protobuf_oneof:"value"`
	Password      string                               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpUsernameOrEmailRequest) Reset() {
	*x = SignUpUsernameOrEmailRequest{}
	mi := &file_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpUsernameOrEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpUsernameOrEmailRequest) ProtoMessage() {}

func (x *SignUpUsernameOrEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpUsernameOrEmailRequest.ProtoReflect.Descriptor instead.
func (*SignUpUsernameOrEmailRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpUsernameOrEmailRequest) GetValue() isSignUpUsernameOrEmailRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SignUpUsernameOrEmailRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Value.(*SignUpUsernameOrEmailRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *SignUpUsernameOrEmailRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Value.(*SignUpUsernameOrEmailRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *SignUpUsernameOrEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type isSignUpUsernameOrEmailRequest_Value interface {
	isSignUpUsernameOrEmailRequest_Value()
}

type SignUpUsernameOrEmailRequest_Username struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3,oneof"`
}

type SignUpUsernameOrEmailRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*SignUpUsernameOrEmailRequest_Username) isSignUpUsernameOrEmailRequest_Value() {}

func (*SignUpUsernameOrEmailRequest_Email) isSignUpUsernameOrEmailRequest_Value() {}

type SignUpUsernameOrEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SignUpUsernameOrEmailResponse_Token
	Value         isSignUpUsernameOrEmailResponse_Value `protobuf_oneof:"value"`
	Error         string                                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpUsernameOrEmailResponse) Reset() {
	*x = SignUpUsernameOrEmailResponse{}
	mi := &file_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpUsernameOrEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpUsernameOrEmailResponse) ProtoMessage() {}

func (x *SignUpUsernameOrEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpUsernameOrEmailResponse.ProtoReflect.Descriptor instead.
func (*SignUpUsernameOrEmailResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpUsernameOrEmailResponse) GetValue() isSignUpUsernameOrEmailResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SignUpUsernameOrEmailResponse) GetToken() string {
	if x != nil {
		if x, ok := x.Value.(*SignUpUsernameOrEmailResponse_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *SignUpUsernameOrEmailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isSignUpUsernameOrEmailResponse_Value interface {
	isSignUpUsernameOrEmailResponse_Value()
}

type SignUpUsernameOrEmailResponse_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

func (*SignUpUsernameOrEmailResponse_Token) isSignUpUsernameOrEmailResponse_Value() {}

type LoginResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponseError) Reset() {
	*x = LoginResponseError{}
	mi := &file_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponseError) ProtoMessage() {}

func (x *LoginResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponseError.ProtoReflect.Descriptor instead.
func (*LoginResponseError) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponseError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SocialMediaLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMediaLoginRequest) Reset() {
	*x = SocialMediaLoginRequest{}
	mi := &file_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMediaLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMediaLoginRequest) ProtoMessage() {}

func (x *SocialMediaLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMediaLoginRequest.ProtoReflect.Descriptor instead.
func (*SocialMediaLoginRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{3}
}

func (x *SocialMediaLoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SocialMediaLoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type SocialUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialUserInfo) Reset() {
	*x = SocialUserInfo{}
	mi := &file_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialUserInfo) ProtoMessage() {}

func (x *SocialUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialUserInfo.ProtoReflect.Descriptor instead.
func (*SocialUserInfo) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{4}
}

func (x *SocialUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SocialUserInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SocialUserInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type SocialMediaLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SocialMediaLoginResponse_ValidatedToken
	Value         isSocialMediaLoginResponse_Value `protobuf_oneof:"value"`
	Error         string                           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMediaLoginResponse) Reset() {
	*x = SocialMediaLoginResponse{}
	mi := &file_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMediaLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMediaLoginResponse) ProtoMessage() {}

func (x *SocialMediaLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMediaLoginResponse.ProtoReflect.Descriptor instead.
func (*SocialMediaLoginResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{5}
}

func (x *SocialMediaLoginResponse) GetValue() isSocialMediaLoginResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SocialMediaLoginResponse) GetValidatedToken() string {
	if x != nil {
		if x, ok := x.Value.(*SocialMediaLoginResponse_ValidatedToken); ok {
			return x.ValidatedToken
		}
	}
	return ""
}

func (x *SocialMediaLoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isSocialMediaLoginResponse_Value interface {
	isSocialMediaLoginResponse_Value()
}

type SocialMediaLoginResponse_ValidatedToken struct {
	ValidatedToken string `protobuf:"bytes,1,opt,name=validated_token,json=validatedToken,proto3,oneof"`
}

func (*SocialMediaLoginResponse_ValidatedToken) isSocialMediaLoginResponse_Value() {}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*LoginRequest_Username
	//	*LoginRequest_Email
	//	*LoginRequest_SocialMediaProvider
	Value         isLoginRequest_Value `protobuf_oneof:"value"`
	Password      string               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetValue() isLoginRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Value.(*LoginRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Value.(*LoginRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *LoginRequest) GetSocialMediaProvider() string {
	if x != nil {
		if x, ok := x.Value.(*LoginRequest_SocialMediaProvider); ok {
			return x.SocialMediaProvider
		}
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type isLoginRequest_Value interface {
	isLoginRequest_Value()
}

type LoginRequest_Username struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type LoginRequest_SocialMediaProvider struct {
	SocialMediaProvider string `protobuf:"bytes,3,opt,name=social_media_provider,json=socialMediaProvider,proto3,oneof"`
}

func (*LoginRequest_Username) isLoginRequest_Value() {}

func (*LoginRequest_Email) isLoginRequest_Value() {}

func (*LoginRequest_SocialMediaProvider) isLoginRequest_Value() {}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*LoginResponse_Token
	//	*LoginResponse_ValidatedEmailOrUsernameLogin
	Value         isLoginResponse_Value `protobuf_oneof:"value"`
	Error         string                `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetValue() isLoginResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		if x, ok := x.Value.(*LoginResponse_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *LoginResponse) GetValidatedEmailOrUsernameLogin() string {
	if x != nil {
		if x, ok := x.Value.(*LoginResponse_ValidatedEmailOrUsernameLogin); ok {
			return x.ValidatedEmailOrUsernameLogin
		}
	}
	return ""
}

func (x *LoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isLoginResponse_Value interface {
	isLoginResponse_Value()
}

type LoginResponse_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type LoginResponse_ValidatedEmailOrUsernameLogin struct {
	ValidatedEmailOrUsernameLogin string `protobuf:"bytes,2,opt,name=validated_email_or_username_login,json=validatedEmailOrUsernameLogin,proto3,oneof"`
}

func (*LoginResponse_Token) isLoginResponse_Value() {}

func (*LoginResponse_ValidatedEmailOrUsernameLogin) isLoginResponse_Value() {}

var File_login_proto protoreflect.FileDescriptor

const file_login_proto_rawDesc = "" +
	"\n" +
	"\vlogin.proto\x12\x06protos\"y\n" +
	"\x1cSignUpUsernameOrEmailRequest\x12\x1c\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpasswordB\a\n" +
	"\x05value\"V\n" +
	"\x1dSignUpUsernameOrEmailResponse\x12\x16\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\a\n" +
	"\x05value\"*\n" +
	"\x12LoginResponseError\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"K\n" +
	"\x17SocialMediaLoginRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"e\n" +
	"\x0eSocialUserInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\"d\n" +
	"\x18SocialMediaLoginResponse\x12)\n" +
	"\x0fvalidated_token\x18\x01 \x01(\tH\x00R\x0evalidatedToken\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\a\n" +
	"\x05value\"\x9f\x01\n" +
	"\fLoginRequest\x12\x1c\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x124\n" +
	"\x15social_media_provider\x18\x03 \x01(\tH\x00R\x13socialMediaProvider\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpasswordB\a\n" +
	"\x05value\"\x92\x01\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x12J\n" +
	"!validated_email_or_username_login\x18\x02 \x01(\tH\x00R\x1dvalidatedEmailOrUsernameLogin\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB\a\n" +
	"\x05value2\x87\x02\n" +
	"\fLoginService\x126\n" +
	"\x05Login\x12\x14.protos.LoginRequest\x1a\x15.protos.LoginResponse\"\x00\x12W\n" +
	"\x10SocialMediaLogin\x12\x1f.protos.SocialMediaLoginRequest\x1a .protos.SocialMediaLoginResponse\"\x00\x12f\n" +
	"\x15SignUpUsernameOrEmail\x12$.protos.SignUpUsernameOrEmailRequest\x1a%.protos.SignUpUsernameOrEmailResponse\"\x00B\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData []byte
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)))
	})
	return file_login_proto_rawDescData
}

var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_login_proto_goTypes = []any{
	(*SignUpUsernameOrEmailRequest)(nil),  // 0: protos.SignUpUsernameOrEmailRequest
	(*SignUpUsernameOrEmailResponse)(nil), // 1: protos.SignUpUsernameOrEmailResponse
	(*LoginResponseError)(nil),            // 2: protos.LoginResponseError
	(*SocialMediaLoginRequest)(nil),       // 3: protos.SocialMediaLoginRequest
	(*SocialUserInfo)(nil),                // 4: protos.SocialUserInfo
	(*SocialMediaLoginResponse)(nil),      // 5: protos.SocialMediaLoginResponse
	(*LoginRequest)(nil),                  // 6: protos.LoginRequest
	(*LoginResponse)(nil),                 // 7: protos.LoginResponse
}
var file_login_proto_depIdxs = []int32{
	6, // 0: protos.LoginService.Login:input_type -> protos.LoginRequest
	3, // 1: protos.LoginService.SocialMediaLogin:input_type -> protos.SocialMediaLoginRequest
	0, // 2: protos.LoginService.SignUpUsernameOrEmail:input_type -> protos.SignUpUsernameOrEmailRequest
	7, // 3: protos.LoginService.Login:output_type -> protos.LoginResponse
	5, // 4: protos.LoginService.SocialMediaLogin:output_type -> protos.SocialMediaLoginResponse
	1, // 5: protos.LoginService.SignUpUsernameOrEmail:output_type -> protos.SignUpUsernameOrEmailResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	file_login_proto_msgTypes[0].OneofWrappers = []any{
		(*SignUpUsernameOrEmailRequest_Username)(nil),
		(*SignUpUsernameOrEmailRequest_Email)(nil),
	}
	file_login_proto_msgTypes[1].OneofWrappers = []any{
		(*SignUpUsernameOrEmailResponse_Token)(nil),
	}
	file_login_proto_msgTypes[5].OneofWrappers = []any{
		(*SocialMediaLoginResponse_ValidatedToken)(nil),
	}
	file_login_proto_msgTypes[6].OneofWrappers = []any{
		(*LoginRequest_Username)(nil),
		(*LoginRequest_Email)(nil),
		(*LoginRequest_SocialMediaProvider)(nil),
	}
	file_login_proto_msgTypes[7].OneofWrappers = []any{
		(*LoginResponse_Token)(nil),
		(*LoginResponse_ValidatedEmailOrUsernameLogin)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
