// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: player.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SonicCharacter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,3,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	SpecialAbility string                 `protobuf:"bytes,4,opt,name=special_ability,json=specialAbility,proto3" json:"special_ability,omitempty"`
	LastUsed       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SonicCharacter) Reset() {
	*x = SonicCharacter{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SonicCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicCharacter) ProtoMessage() {}

func (x *SonicCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicCharacter.ProtoReflect.Descriptor instead.
func (*SonicCharacter) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *SonicCharacter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SonicCharacter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SonicCharacter) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *SonicCharacter) GetSpecialAbility() string {
	if x != nil {
		return x.SpecialAbility
	}
	return ""
}

func (x *SonicCharacter) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

type FriendList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendList) Reset() {
	*x = FriendList{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendList) ProtoMessage() {}

func (x *FriendList) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendList.ProtoReflect.Descriptor instead.
func (*FriendList) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *FriendList) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Player struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                  string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	SocialsLinked          string                 `protobuf:"bytes,4,opt,name=socials_linked,json=socialsLinked,proto3" json:"socials_linked,omitempty"`
	SonicCharacter         []*SonicCharacter      `protobuf:"bytes,5,rep,name=sonic_character,json=sonicCharacter,proto3" json:"sonic_character,omitempty"`
	TotalPoints            int64                  `protobuf:"varint,6,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	TotalSuccessfulAnswers int64                  `protobuf:"varint,7,opt,name=total_successful_answers,json=totalSuccessfulAnswers,proto3" json:"total_successful_answers,omitempty"`
	TotalAnswers           int64                  `protobuf:"varint,8,opt,name=total_answers,json=totalAnswers,proto3" json:"total_answers,omitempty"`
	Role                   string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	Friends                []*FriendList          `protobuf:"bytes,10,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Player) GetSocialsLinked() string {
	if x != nil {
		return x.SocialsLinked
	}
	return ""
}

func (x *Player) GetSonicCharacter() []*SonicCharacter {
	if x != nil {
		return x.SonicCharacter
	}
	return nil
}

func (x *Player) GetTotalPoints() int64 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *Player) GetTotalSuccessfulAnswers() int64 {
	if x != nil {
		return x.TotalSuccessfulAnswers
	}
	return 0
}

func (x *Player) GetTotalAnswers() int64 {
	if x != nil {
		return x.TotalAnswers
	}
	return 0
}

func (x *Player) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Player) GetFriends() []*FriendList {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x01\n" +
	"\x0eSonicCharacter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fprofile_picture\x18\x03 \x01(\tR\x0eprofilePicture\x12'\n" +
	"\x0fspecial_ability\x18\x04 \x01(\tR\x0especialAbility\x127\n" +
	"\tlast_used\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\"(\n" +
	"\n" +
	"FriendList\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\xde\x02\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0esocials_linked\x18\x04 \x01(\tR\rsocialsLinked\x12?\n" +
	"\x0fsonic_character\x18\x05 \x03(\v2\x16.protos.SonicCharacterR\x0esonicCharacter\x12!\n" +
	"\ftotal_points\x18\x06 \x01(\x03R\vtotalPoints\x128\n" +
	"\x18total_successful_answers\x18\a \x01(\x03R\x16totalSuccessfulAnswers\x12#\n" +
	"\rtotal_answers\x18\b \x01(\x03R\ftotalAnswers\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12,\n" +
	"\afriends\x18\n" +
	" \x03(\v2\x12.protos.FriendListR\afriendsB\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_player_proto_goTypes = []any{
	(*SonicCharacter)(nil),        // 0: protos.SonicCharacter
	(*FriendList)(nil),            // 1: protos.FriendList
	(*Player)(nil),                // 2: protos.Player
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_player_proto_depIdxs = []int32{
	3, // 0: protos.SonicCharacter.last_used:type_name -> google.protobuf.Timestamp
	0, // 1: protos.Player.sonic_character:type_name -> protos.SonicCharacter
	1, // 2: protos.Player.friends:type_name -> protos.FriendList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
