// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: roomdata.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomData struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Players     []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Code        string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Mode        IndividualGameModes    `protobuf:"varint,7,opt,name=mode,proto3,enum=protos.IndividualGameModes" json:"mode,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*RoomData_TriviaCategory
	//	*RoomData_GuessThatSongCategory
	Value          isRoomData_Value `protobuf_oneof:"value"`
	Leaderboard    *RoomLeaderboard `protobuf:"bytes,10,opt,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	MaxRoomSize    int64            `protobuf:"varint,11,opt,name=max_room_size,json=maxRoomSize,proto3" json:"max_room_size,omitempty"`
	AmountOfRounds int64            `protobuf:"varint,12,opt,name=amount_of_rounds,json=amountOfRounds,proto3" json:"amount_of_rounds,omitempty"`
	ReadOnly       bool             `protobuf:"varint,13,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	IsPrivate      bool             `protobuf:"varint,14,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Jukebox        *JukeBox         `protobuf:"bytes,15,opt,name=jukebox,proto3" json:"jukebox,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomData) Reset() {
	*x = RoomData{}
	mi := &file_roomdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomData) ProtoMessage() {}

func (x *RoomData) ProtoReflect() protoreflect.Message {
	mi := &file_roomdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomData.ProtoReflect.Descriptor instead.
func (*RoomData) Descriptor() ([]byte, []int) {
	return file_roomdata_proto_rawDescGZIP(), []int{0}
}

func (x *RoomData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomData) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomData) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *RoomData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoomData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoomData) GetMode() IndividualGameModes {
	if x != nil {
		return x.Mode
	}
	return IndividualGameModes_INDIVIDUAL_GAME_MODES_UNSPECIFIED
}

func (x *RoomData) GetValue() isRoomData_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RoomData) GetTriviaCategory() TriviaCategories {
	if x != nil {
		if x, ok := x.Value.(*RoomData_TriviaCategory); ok {
			return x.TriviaCategory
		}
	}
	return TriviaCategories_TRIVIA_CATEGORIES_TRIVIA_CATEGORY_UNSPECIFIED
}

func (x *RoomData) GetGuessThatSongCategory() GuessThatSongCategories {
	if x != nil {
		if x, ok := x.Value.(*RoomData_GuessThatSongCategory); ok {
			return x.GuessThatSongCategory
		}
	}
	return GuessThatSongCategories_GUESS_THAT_SONG_CATEGORIES_GUESS_THAT_SONG_CATEGORY_UNSPECIFIED
}

func (x *RoomData) GetLeaderboard() *RoomLeaderboard {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *RoomData) GetMaxRoomSize() int64 {
	if x != nil {
		return x.MaxRoomSize
	}
	return 0
}

func (x *RoomData) GetAmountOfRounds() int64 {
	if x != nil {
		return x.AmountOfRounds
	}
	return 0
}

func (x *RoomData) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *RoomData) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *RoomData) GetJukebox() *JukeBox {
	if x != nil {
		return x.Jukebox
	}
	return nil
}

type isRoomData_Value interface {
	isRoomData_Value()
}

type RoomData_TriviaCategory struct {
	TriviaCategory TriviaCategories `protobuf:"varint,8,opt,name=trivia_category,json=triviaCategory,proto3,enum=protos.TriviaCategories,oneof"`
}

type RoomData_GuessThatSongCategory struct {
	GuessThatSongCategory GuessThatSongCategories `protobuf:"varint,9,opt,name=guess_that_song_category,json=guessThatSongCategory,proto3,enum=protos.GuessThatSongCategories,oneof"`
}

func (*RoomData_TriviaCategory) isRoomData_Value() {}

func (*RoomData_GuessThatSongCategory) isRoomData_Value() {}

type JukeBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []string               `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JukeBox) Reset() {
	*x = JukeBox{}
	mi := &file_roomdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JukeBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JukeBox) ProtoMessage() {}

func (x *JukeBox) ProtoReflect() protoreflect.Message {
	mi := &file_roomdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JukeBox.ProtoReflect.Descriptor instead.
func (*JukeBox) Descriptor() ([]byte, []int) {
	return file_roomdata_proto_rawDescGZIP(), []int{1}
}

func (x *JukeBox) GetSongs() []string {
	if x != nil {
		return x.Songs
	}
	return nil
}

var File_roomdata_proto protoreflect.FileDescriptor

const file_roomdata_proto_rawDesc = "" +
	"\n" +
	"\x0eroomdata.proto\x12\x06protos\x1a\x0fgamemodes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11leaderboard.proto\x1a\fplayer.proto\"\xc3\x05\n" +
	"\bRoomData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\aplayers\x18\x02 \x03(\v2\x0e.protos.PlayerR\aplayers\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12/\n" +
	"\x04mode\x18\a \x01(\x0e2\x1b.protos.IndividualGameModesR\x04mode\x12C\n" +
	"\x0ftrivia_category\x18\b \x01(\x0e2\x18.protos.TriviaCategoriesH\x00R\x0etriviaCategory\x12Z\n" +
	"\x18guess_that_song_category\x18\t \x01(\x0e2\x1f.protos.GuessThatSongCategoriesH\x00R\x15guessThatSongCategory\x129\n" +
	"\vleaderboard\x18\n" +
	" \x01(\v2\x17.protos.RoomLeaderboardR\vleaderboard\x12\"\n" +
	"\rmax_room_size\x18\v \x01(\x03R\vmaxRoomSize\x12(\n" +
	"\x10amount_of_rounds\x18\f \x01(\x03R\x0eamountOfRounds\x12\x1b\n" +
	"\tread_only\x18\r \x01(\bR\breadOnly\x12\x1d\n" +
	"\n" +
	"is_private\x18\x0e \x01(\bR\tisPrivate\x12)\n" +
	"\ajukebox\x18\x0f \x01(\v2\x0f.protos.JukeBoxR\ajukeboxB\a\n" +
	"\x05value\"\x1f\n" +
	"\aJukeBox\x12\x14\n" +
	"\x05songs\x18\x01 \x03(\tR\x05songsB\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_roomdata_proto_rawDescOnce sync.Once
	file_roomdata_proto_rawDescData []byte
)

func file_roomdata_proto_rawDescGZIP() []byte {
	file_roomdata_proto_rawDescOnce.Do(func() {
		file_roomdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_roomdata_proto_rawDesc), len(file_roomdata_proto_rawDesc)))
	})
	return file_roomdata_proto_rawDescData
}

var file_roomdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_roomdata_proto_goTypes = []any{
	(*RoomData)(nil),              // 0: protos.RoomData
	(*JukeBox)(nil),               // 1: protos.JukeBox
	(*Player)(nil),                // 2: protos.Player
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(IndividualGameModes)(0),      // 4: protos.IndividualGameModes
	(TriviaCategories)(0),         // 5: protos.TriviaCategories
	(GuessThatSongCategories)(0),  // 6: protos.GuessThatSongCategories
	(*RoomLeaderboard)(nil),       // 7: protos.RoomLeaderboard
}
var file_roomdata_proto_depIdxs = []int32{
	2, // 0: protos.RoomData.players:type_name -> protos.Player
	3, // 1: protos.RoomData.last_updated:type_name -> google.protobuf.Timestamp
	3, // 2: protos.RoomData.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: protos.RoomData.mode:type_name -> protos.IndividualGameModes
	5, // 4: protos.RoomData.trivia_category:type_name -> protos.TriviaCategories
	6, // 5: protos.RoomData.guess_that_song_category:type_name -> protos.GuessThatSongCategories
	7, // 6: protos.RoomData.leaderboard:type_name -> protos.RoomLeaderboard
	1, // 7: protos.RoomData.jukebox:type_name -> protos.JukeBox
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_roomdata_proto_init() }
func file_roomdata_proto_init() {
	if File_roomdata_proto != nil {
		return
	}
	file_gamemodes_proto_init()
	file_leaderboard_proto_init()
	file_player_proto_init()
	file_roomdata_proto_msgTypes[0].OneofWrappers = []any{
		(*RoomData_TriviaCategory)(nil),
		(*RoomData_GuessThatSongCategory)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_roomdata_proto_rawDesc), len(file_roomdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roomdata_proto_goTypes,
		DependencyIndexes: file_roomdata_proto_depIdxs,
		MessageInfos:      file_roomdata_proto_msgTypes,
	}.Build()
	File_roomdata_proto = out.File
	file_roomdata_proto_goTypes = nil
	file_roomdata_proto_depIdxs = nil
}
