// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trivia.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,3,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_trivia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Answer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Answer) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type AnswerOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*Answer              `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerOptions) Reset() {
	*x = AnswerOptions{}
	mi := &file_trivia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerOptions) ProtoMessage() {}

func (x *AnswerOptions) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerOptions.ProtoReflect.Descriptor instead.
func (*AnswerOptions) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerOptions) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Hint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hint) Reset() {
	*x = Hint{}
	mi := &file_trivia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hint) ProtoMessage() {}

func (x *Hint) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hint.ProtoReflect.Descriptor instead.
func (*Hint) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{2}
}

func (x *Hint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hint) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Question struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text               string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Category           string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty         string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	AnswerOptions      *AnswerOptions         `protobuf:"bytes,5,opt,name=answer_options,json=answerOptions,proto3" json:"answer_options,omitempty"`
	Points             int32                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	Hints              []*Hint                `protobuf:"bytes,7,rep,name=hints,proto3" json:"hints,omitempty"`
	PictureForQuestion string                 `protobuf:"bytes,8,opt,name=picture_for_question,json=pictureForQuestion,proto3" json:"picture_for_question,omitempty"`
	PictureUrl         *string                `protobuf:"bytes,9,opt,name=picture_url,json=pictureUrl,proto3,oneof" json:"picture_url,omitempty"`
	CreatedBy          string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_trivia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{3}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Question) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Question) GetAnswerOptions() *AnswerOptions {
	if x != nil {
		return x.AnswerOptions
	}
	return nil
}

func (x *Question) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *Question) GetHints() []*Hint {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *Question) GetPictureForQuestion() string {
	if x != nil {
		return x.PictureForQuestion
	}
	return ""
}

func (x *Question) GetPictureUrl() string {
	if x != nil && x.PictureUrl != nil {
		return *x.PictureUrl
	}
	return ""
}

func (x *Question) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetRandomQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	HowManyRounds int32                  `protobuf:"varint,2,opt,name=how_many_rounds,json=howManyRounds,proto3" json:"how_many_rounds,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuestionsRequest) Reset() {
	*x = GetRandomQuestionsRequest{}
	mi := &file_trivia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuestionsRequest) ProtoMessage() {}

func (x *GetRandomQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetRandomQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{4}
}

func (x *GetRandomQuestionsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetRandomQuestionsRequest) GetHowManyRounds() int32 {
	if x != nil {
		return x.HowManyRounds
	}
	return 0
}

func (x *GetRandomQuestionsRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

type GetRandomQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuestionsResponse) Reset() {
	*x = GetRandomQuestionsResponse{}
	mi := &file_trivia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuestionsResponse) ProtoMessage() {}

func (x *GetRandomQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetRandomQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{5}
}

func (x *GetRandomQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CheckAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerId      string                 `protobuf:"bytes,2,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAnswerRequest) Reset() {
	*x = CheckAnswerRequest{}
	mi := &file_trivia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAnswerRequest) ProtoMessage() {}

func (x *CheckAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAnswerRequest.ProtoReflect.Descriptor instead.
func (*CheckAnswerRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{6}
}

func (x *CheckAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *CheckAnswerRequest) GetAnswerId() string {
	if x != nil {
		return x.AnswerId
	}
	return ""
}

type CheckAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCorrect     bool                   `protobuf:"varint,1,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAnswerResponse) Reset() {
	*x = CheckAnswerResponse{}
	mi := &file_trivia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAnswerResponse) ProtoMessage() {}

func (x *CheckAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAnswerResponse.ProtoReflect.Descriptor instead.
func (*CheckAnswerResponse) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{7}
}

func (x *CheckAnswerResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	AnswerOptions *AnswerOptions         `protobuf:"bytes,5,opt,name=answer_options,json=answerOptions,proto3" json:"answer_options,omitempty"`
	Points        int32                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	Hints         []*Hint                `protobuf:"bytes,7,rep,name=hints,proto3" json:"hints,omitempty"`
	PictureFile   []byte                 `protobuf:"bytes,8,opt,name=picture_file,json=pictureFile,proto3,oneof" json:"picture_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_trivia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateQuestionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateQuestionRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *UpdateQuestionRequest) GetAnswerOptions() *AnswerOptions {
	if x != nil {
		return x.AnswerOptions
	}
	return nil
}

func (x *UpdateQuestionRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *UpdateQuestionRequest) GetHints() []*Hint {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *UpdateQuestionRequest) GetPictureFile() []byte {
	if x != nil {
		return x.PictureFile
	}
	return nil
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_trivia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_trivia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionResponse) Reset() {
	*x = DeleteQuestionResponse{}
	mi := &file_trivia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionResponse) ProtoMessage() {}

func (x *DeleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteQuestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_trivia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{12}
}

func (x *CreateQuestionRequest) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_trivia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{13}
}

func (x *CreateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type GetAnsweredQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnsweredQuestionsRequest) Reset() {
	*x = GetAnsweredQuestionsRequest{}
	mi := &file_trivia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnsweredQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnsweredQuestionsRequest) ProtoMessage() {}

func (x *GetAnsweredQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnsweredQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetAnsweredQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{14}
}

func (x *GetAnsweredQuestionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAnsweredQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnsweredQuestionsResponse) Reset() {
	*x = GetAnsweredQuestionsResponse{}
	mi := &file_trivia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnsweredQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnsweredQuestionsResponse) ProtoMessage() {}

func (x *GetAnsweredQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnsweredQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetAnsweredQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{15}
}

func (x *GetAnsweredQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetRandomQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuestionRequest) Reset() {
	*x = GetRandomQuestionRequest{}
	mi := &file_trivia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuestionRequest) ProtoMessage() {}

func (x *GetRandomQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetRandomQuestionRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{16}
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_trivia_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{17}
}

func (x *GetQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_trivia_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivia_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_trivia_proto_rawDescGZIP(), []int{18}
}

func (x *GetQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

var File_trivia_proto protoreflect.FileDescriptor

const file_trivia_proto_rawDesc = "" +
	"\n" +
	"\ftrivia.proto\x12\x06protos\"K\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x03 \x01(\bR\tisCorrect\"9\n" +
	"\rAnswerOptions\x12(\n" +
	"\aanswers\x18\x01 \x03(\v2\x0e.protos.AnswerR\aanswers\"*\n" +
	"\x04Hint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xeb\x02\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12<\n" +
	"\x0eanswer_options\x18\x05 \x01(\v2\x15.protos.AnswerOptionsR\ranswerOptions\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x05R\x06points\x12\"\n" +
	"\x05hints\x18\a \x03(\v2\f.protos.HintR\x05hints\x120\n" +
	"\x14picture_for_question\x18\b \x01(\tR\x12pictureForQuestion\x12$\n" +
	"\vpicture_url\x18\t \x01(\tH\x00R\n" +
	"pictureUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedByB\x0e\n" +
	"\f_picture_url\"\x7f\n" +
	"\x19GetRandomQuestionsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12&\n" +
	"\x0fhow_many_rounds\x18\x02 \x01(\x05R\rhowManyRounds\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\"L\n" +
	"\x1aGetRandomQuestionsResponse\x12.\n" +
	"\tquestions\x18\x01 \x03(\v2\x10.protos.QuestionR\tquestions\"R\n" +
	"\x12CheckAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1b\n" +
	"\tanswer_id\x18\x02 \x01(\tR\banswerId\"4\n" +
	"\x13CheckAnswerResponse\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x01 \x01(\bR\tisCorrect\"\xaa\x02\n" +
	"\x15UpdateQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12<\n" +
	"\x0eanswer_options\x18\x05 \x01(\v2\x15.protos.AnswerOptionsR\ranswerOptions\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x05R\x06points\x12\"\n" +
	"\x05hints\x18\a \x03(\v2\f.protos.HintR\x05hints\x12&\n" +
	"\fpicture_file\x18\b \x01(\fH\x00R\vpictureFile\x88\x01\x01B\x0f\n" +
	"\r_picture_file\"F\n" +
	"\x16UpdateQuestionResponse\x12,\n" +
	"\bquestion\x18\x01 \x01(\v2\x10.protos.QuestionR\bquestion\"'\n" +
	"\x15DeleteQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteQuestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x15CreateQuestionRequest\x12,\n" +
	"\bquestion\x18\x01 \x01(\v2\x10.protos.QuestionR\bquestion\"F\n" +
	"\x16CreateQuestionResponse\x12,\n" +
	"\bquestion\x18\x01 \x01(\v2\x10.protos.QuestionR\bquestion\"6\n" +
	"\x1bGetAnsweredQuestionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\x1cGetAnsweredQuestionsResponse\x12.\n" +
	"\tquestions\x18\x01 \x03(\v2\x10.protos.QuestionR\tquestions\"\x1a\n" +
	"\x18GetRandomQuestionRequest\"$\n" +
	"\x12GetQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13GetQuestionResponse\x12,\n" +
	"\bquestion\x18\x01 \x01(\v2\x10.protos.QuestionR\bquestion2\xe0\x04\n" +
	"\rTriviaService\x12H\n" +
	"\vGetQuestion\x12\x1a.protos.GetQuestionRequest\x1a\x1b.protos.GetQuestionResponse\"\x00\x12]\n" +
	"\x12GetRandomQuestions\x12!.protos.GetRandomQuestionsRequest\x1a\".protos.GetRandomQuestionsResponse\"\x00\x12Q\n" +
	"\x0eUpdateQuestion\x12\x1d.protos.UpdateQuestionRequest\x1a\x1e.protos.UpdateQuestionResponse\"\x00\x12Q\n" +
	"\x0eDeleteQuestion\x12\x1d.protos.DeleteQuestionRequest\x1a\x1e.protos.DeleteQuestionResponse\"\x00\x12Q\n" +
	"\x0eCreateQuestion\x12\x1d.protos.CreateQuestionRequest\x1a\x1e.protos.CreateQuestionResponse\"\x00\x12c\n" +
	"\x14GetAnsweredQuestions\x12#.protos.GetAnsweredQuestionsRequest\x1a$.protos.GetAnsweredQuestionsResponse\"\x00\x12H\n" +
	"\vCheckAnswer\x12\x1a.protos.CheckAnswerRequest\x1a\x1b.protos.CheckAnswerResponse\"\x00B\x1dZ\x1bsonic-trivia/backend/protosb\x06proto3"

var (
	file_trivia_proto_rawDescOnce sync.Once
	file_trivia_proto_rawDescData []byte
)

func file_trivia_proto_rawDescGZIP() []byte {
	file_trivia_proto_rawDescOnce.Do(func() {
		file_trivia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trivia_proto_rawDesc), len(file_trivia_proto_rawDesc)))
	})
	return file_trivia_proto_rawDescData
}

var file_trivia_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_trivia_proto_goTypes = []any{
	(*Answer)(nil),                       // 0: protos.Answer
	(*AnswerOptions)(nil),                // 1: protos.AnswerOptions
	(*Hint)(nil),                         // 2: protos.Hint
	(*Question)(nil),                     // 3: protos.Question
	(*GetRandomQuestionsRequest)(nil),    // 4: protos.GetRandomQuestionsRequest
	(*GetRandomQuestionsResponse)(nil),   // 5: protos.GetRandomQuestionsResponse
	(*CheckAnswerRequest)(nil),           // 6: protos.CheckAnswerRequest
	(*CheckAnswerResponse)(nil),          // 7: protos.CheckAnswerResponse
	(*UpdateQuestionRequest)(nil),        // 8: protos.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),       // 9: protos.UpdateQuestionResponse
	(*DeleteQuestionRequest)(nil),        // 10: protos.DeleteQuestionRequest
	(*DeleteQuestionResponse)(nil),       // 11: protos.DeleteQuestionResponse
	(*CreateQuestionRequest)(nil),        // 12: protos.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),       // 13: protos.CreateQuestionResponse
	(*GetAnsweredQuestionsRequest)(nil),  // 14: protos.GetAnsweredQuestionsRequest
	(*GetAnsweredQuestionsResponse)(nil), // 15: protos.GetAnsweredQuestionsResponse
	(*GetRandomQuestionRequest)(nil),     // 16: protos.GetRandomQuestionRequest
	(*GetQuestionRequest)(nil),           // 17: protos.GetQuestionRequest
	(*GetQuestionResponse)(nil),          // 18: protos.GetQuestionResponse
}
var file_trivia_proto_depIdxs = []int32{
	0,  // 0: protos.AnswerOptions.answers:type_name -> protos.Answer
	1,  // 1: protos.Question.answer_options:type_name -> protos.AnswerOptions
	2,  // 2: protos.Question.hints:type_name -> protos.Hint
	3,  // 3: protos.GetRandomQuestionsResponse.questions:type_name -> protos.Question
	1,  // 4: protos.UpdateQuestionRequest.answer_options:type_name -> protos.AnswerOptions
	2,  // 5: protos.UpdateQuestionRequest.hints:type_name -> protos.Hint
	3,  // 6: protos.UpdateQuestionResponse.question:type_name -> protos.Question
	3,  // 7: protos.CreateQuestionRequest.question:type_name -> protos.Question
	3,  // 8: protos.CreateQuestionResponse.question:type_name -> protos.Question
	3,  // 9: protos.GetAnsweredQuestionsResponse.questions:type_name -> protos.Question
	3,  // 10: protos.GetQuestionResponse.question:type_name -> protos.Question
	17, // 11: protos.TriviaService.GetQuestion:input_type -> protos.GetQuestionRequest
	4,  // 12: protos.TriviaService.GetRandomQuestions:input_type -> protos.GetRandomQuestionsRequest
	8,  // 13: protos.TriviaService.UpdateQuestion:input_type -> protos.UpdateQuestionRequest
	10, // 14: protos.TriviaService.DeleteQuestion:input_type -> protos.DeleteQuestionRequest
	12, // 15: protos.TriviaService.CreateQuestion:input_type -> protos.CreateQuestionRequest
	14, // 16: protos.TriviaService.GetAnsweredQuestions:input_type -> protos.GetAnsweredQuestionsRequest
	6,  // 17: protos.TriviaService.CheckAnswer:input_type -> protos.CheckAnswerRequest
	18, // 18: protos.TriviaService.GetQuestion:output_type -> protos.GetQuestionResponse
	5,  // 19: protos.TriviaService.GetRandomQuestions:output_type -> protos.GetRandomQuestionsResponse
	9,  // 20: protos.TriviaService.UpdateQuestion:output_type -> protos.UpdateQuestionResponse
	11, // 21: protos.TriviaService.DeleteQuestion:output_type -> protos.DeleteQuestionResponse
	13, // 22: protos.TriviaService.CreateQuestion:output_type -> protos.CreateQuestionResponse
	15, // 23: protos.TriviaService.GetAnsweredQuestions:output_type -> protos.GetAnsweredQuestionsResponse
	7,  // 24: protos.TriviaService.CheckAnswer:output_type -> protos.CheckAnswerResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_trivia_proto_init() }
func file_trivia_proto_init() {
	if File_trivia_proto != nil {
		return
	}
	file_trivia_proto_msgTypes[3].OneofWrappers = []any{}
	file_trivia_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trivia_proto_rawDesc), len(file_trivia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trivia_proto_goTypes,
		DependencyIndexes: file_trivia_proto_depIdxs,
		MessageInfos:      file_trivia_proto_msgTypes,
	}.Build()
	File_trivia_proto = out.File
	file_trivia_proto_goTypes = nil
	file_trivia_proto_depIdxs = nil
}
